var title = {french: "Corps et personnalité"}

var flashcards = [
  { chinese: "身体", pinyin: "shēnti", french: "corps" },
  { chinese: "外貌", pinyin: "wàimào", french: "apparence" },
  { chinese: "眼睛", pinyin: "yǎnjīng", french: "yeux" },
  { chinese: "鼻子", pinyin: "bízi", french: "nez" },
  { chinese: "耳朵", pinyin: "ěrduo", french: "oreille" },
  { chinese: "个子", pinyin: "gèzi", french: "taille" },
  { chinese: "胳膊", pinyin: "gē bo", french: "bras" },
  { chinese: "腿", pinyin: "tuǐ", french: "jambe" },
  { chinese: "嘴", pinyin: "zuǐ", french: "bouche" },
  { chinese: "脚", pinyin: "jiǎo", french: "pied" },
  { chinese: "背", pinyin: "bèi", french: "dos" },
  { chinese: "头发", pinyin: "tóufà", french: "cheveux" },
  { chinese: "手", pinyin: "shǒu", french: "main" },
  { chinese: "脸", pinyin: "liǎn", french: "visage" },
  { chinese: "短", pinyin: "duǎn", french: "court" },
  { chinese: "颜色", pinyin: "yánsè", french: "couleur" },
  { chinese: "高", pinyin: "gāo", french: "grand" },
  { chinese: "矮", pinyin: "ǎi", french: "petit (en taille)" },
  { chinese: "胖", pinyin: "pàng", french: "gros" },
  { chinese: "瘦", pinyin: "shòu", french: "mince" },
  { chinese: "圆", pinyin: "yuán", french: "rond" },
  { chinese: "尖", pinyin: "jiān", french: "pointu" },
  { chinese: "卷卷的", pinyin: "juǎnjuǎn de", french: "bouclé" },
  { chinese: "乱", pinyin: "luàn", french: "messy" },
  { chinese: "长长的", pinyin: "chángchángde", french: "long" },
  { chinese: "直直的", pinyin: "zhízhíde", french: "droit" },
  { chinese: "性格", pinyin: "xìng gé", french: "personnalité" },
  { chinese: "风格", pinyin: "fēng gé", french: "style" },
  { chinese: "酷", pinyin: "kù", french: "cool" },
  { chinese: "冷", pinyin: "lěng", french: "froid" },
  { chinese: "爱玩儿", pinyin: "ài wánr", french: "aimer jouer" },
  { chinese: "爱开玩笑", pinyin: "ài kāiwánxiào", french: "aimer faire des blagues" },
  { chinese: "自然", pinyin: "zìrán", french: "naturel" },
  { chinese: "假", pinyin: "jiǎ", french: "faux" },
  { chinese: "开朗", pinyin: "kāi lǎng", french: "joyeux, ouvert" },
  { chinese: "帅哥", pinyin: "shuàigē", french: "beau gosse" },
  { chinese: "小鲜肉", pinyin: "xiǎo xiān ròu", french: "jeune, frais (doué de talent, qui a du look)" },
  { chinese: "校花", pinyin: "xiào huā", french: "la fille populaire de l'école" },
  { chinese: "热情", pinyin: "rèqíng", french: "chaleureux" },
  { chinese: "淘气", pinyin: "táo qì", french: "coquin" },
  { chinese: "做自己", pinyin: "zuò zìjǐ", french: "être soi-même" },
  { chinese: "骄傲", pinyin: "jiāo ào", french: "fier" },
  { chinese: "美女", pinyin: "měinǚ", french: "belle fille" },
  { chinese: "校草", pinyin: "xiào cǎo", french: "le garçon populaire de l'école" },
  { chinese: "自信", pinyin: "zìxìn", french: "confiance en soi" },
  { chinese: "靓", pinyin: "liàng", french: "beau, bon, joli" },
  { chinese: "有 个性", pinyin: "yǒu gèxìng", french: "a de la forte personnalité" },
  { chinese: "热心", pinyin: "rèxīn", french: "gentil" },
  { chinese: "靓仔", pinyin: "liàng zǎi", french: "beau garçon" },
  { chinese: "坏", pinyin: "huài", french: "méchant"},
  { chinese: "学习好", pinyin: "xué xí hǎo", french: "bon élève" },
  { chinese: "班长", pinyin: "bān zhǎng", french: "chef de classe" },
  { chinese: "用功", pinyin: "yòng gōng", french: "studieux" },
  { chinese: "理想", pinyin: "lǐ xiǎng", french: "idéal" },
  { chinese: "安静", pinyin: "ān jìng", french: "silencieux, calme" },
  { chinese: "衣服", pinyin: "yī fú", french: "vêtements" },
  { chinese: "时髦", pinyin: "shí máo", french: "à la mode" },
  { chinese: "有型", pinyin: "yǒu xíng", french: "avoir du style" },
  { chinese: "有美感", pinyin: "yǒu měi gǎn", french: "avoir le sens de la beauté" },
  { chinese: "干净", pinyin: "gān jìng", french: "propre" },
  { chinese: "随意", pinyin: "suí yì", french: "freestyle" },
  { chinese: "穿", pinyin: "chuān", french: "s'habiller" },
  { chinese: "戴", pinyin: "dài", french: "mettre des accessoires" },
  { chinese: "穿搭", pinyin: "chuān dā", french: "outfit" },
];
