export var title = "HSK 2";
export var date = "2025-10-29";

export var flashcards = [
{ chinese: "您", pinyin: "nín", french: "you" },
{ chinese: "它", pinyin: "tā", french: "it" },
{ chinese: "大家", pinyin: "dàjiā", french: "everyone" },
{ chinese: "每", pinyin: "měi", french: "every" },
{ chinese: "为什么", pinyin: "wèishénme", french: "why" },
{ chinese: "零", pinyin: "líng", french: "zero" },
{ chinese: "两", pinyin: "liǎng", french: "two" },
{ chinese: "百", pinyin: "bǎi", french: "hundred" },
{ chinese: "千", pinyin: "qiān", french: "thousand" },
{ chinese: "第一", pinyin: "dìyī", french: "first" },
{ chinese: "次", pinyin: "cì", french: "time" },
{ chinese: "件", pinyin: "jiàn", french: "piece" },
{ chinese: "别", pinyin: "bié", french: "don't" },
{ chinese: "非常", pinyin: "fēicháng", french: "very" },
{ chinese: "也", pinyin: "yě", french: "also" },
{ chinese: "还", pinyin: "hái", french: "still" },
{ chinese: "最", pinyin: "zuì", french: "most" },
{ chinese: "真", pinyin: "zhēn", french: "really" },
{ chinese: "正在", pinyin: "zhèngzài", french: "in the process of" },
{ chinese: "已经", pinyin: "yǐjīng", french: "already" },
{ chinese: "一起", pinyin: "yìqǐ", french: "together" },
{ chinese: "再", pinyin: "zài", french: "again" },
{ chinese: "就", pinyin: "jiù", french: "then" },
{ chinese: "因为……所以……", pinyin: "yīnwèi…suǒyǐ…", french: "because...so..." },
{ chinese: "虽然……但是……", pinyin: "suīrán…dànshì…", french: "although...but..." },
{ chinese: "从", pinyin: "cóng", french: "from" },
{ chinese: "比", pinyin: "bǐ", french: "compare" },
{ chinese: "往", pinyin: "wǎng", french: "to" },
{ chinese: "离", pinyin: "lí", french: "away from" },
{ chinese: "得", pinyin: "de", french: "(structural particle)" },
{ chinese: "着", pinyin: "zhe", french: "(aspect particle)" },
{ chinese: "过", pinyin: "guò", french: "(experience particle)" },
{ chinese: "吧", pinyin: "ba", french: "(modal particle)" },
{ chinese: "机场", pinyin: "jīchǎng", french: "airport" },
{ chinese: "教室", pinyin: "jiàoshì", french: "classroom" },
{ chinese: "房间", pinyin: "fángjiān", french: "room" },
{ chinese: "路", pinyin: "lù", french: "road" },
{ chinese: "左边", pinyin: "zuǒbiān", french: "left" },
{ chinese: "右边", pinyin: "yòubiān", french: "right" },
{ chinese: "外", pinyin: "wài", french: "outside" },
{ chinese: "旁边", pinyin: "pángbiān", french: "side" },
{ chinese: "一下", pinyin: "yīxià", french: "briefly" },
{ chinese: "早上", pinyin: "zǎoshàng", french: "morning" },
{ chinese: "晚上", pinyin: "wǎnshàng", french: "night" },
{ chinese: "小时", pinyin: "xiǎoshí", french: "hour" },
{ chinese: "时间", pinyin: "shíjiān", french: "time" },
{ chinese: "去年", pinyin: "qùnián", french: "last year" },
{ chinese: "日", pinyin: "rì", french: "day" },
{ chinese: "生日", pinyin: "shēngrì", french: "birthday" },
{ chinese: "哥哥", pinyin: "gēge", french: "older brother" },
{ chinese: "姐姐", pinyin: "jiějie", french: "older sister" },
{ chinese: "弟弟", pinyin: "dìdi", french: "younger brother" },
{ chinese: "妹妹", pinyin: "mèimei", french: "younger sister" },
{ chinese: "丈夫", pinyin: "zhàngfu", french: "husband" },
{ chinese: "妻子", pinyin: "qīzi", french: "wife" },
{ chinese: "孩子", pinyin: "háizi", french: "child" },
{ chinese: "男人", pinyin: "nánrén", french: "man" },
{ chinese: "女人", pinyin: "nǚrén", french: "woman" },
{ chinese: "服务员", pinyin: "fúwùyuán", french: "waiter" },
{ chinese: "鱼", pinyin: "yú", french: "fish" },
{ chinese: "羊肉", pinyin: "yángròu", french: "mutton" },
{ chinese: "牛奶", pinyin: "niúnǎi", french: "milk" },
{ chinese: "鸡蛋", pinyin: "jīdàn", french: "egg" },
{ chinese: "西瓜", pinyin: "xīguā", french: "watermelon" },
{ chinese: "咖啡", pinyin: "kāfēi", french: "coffee" },
{ chinese: "雪", pinyin: "xuě", french: "snow" },
{ chinese: "药", pinyin: "yào", french: "medicine" },
{ chinese: "手机", pinyin: "shǒujī", french: "cellphone" },
{ chinese: "手表", pinyin: "shǒubiǎo", french: "watch" },
{ chinese: "眼睛", pinyin: "yǎnjīng", french: "eye" },
{ chinese: "身体", pinyin: "shēntǐ", french: "body" },
{ chinese: "公共汽车", pinyin: "gōnggòngqìchē", french: "bus" },
{ chinese: "报纸", pinyin: "bàozhǐ", french: "newspaper" },
{ chinese: "门", pinyin: "mén", french: "door" },
{ chinese: "题", pinyin: "tí", french: "question" },
{ chinese: "课", pinyin: "kè", french: "lesson" },
{ chinese: "姓", pinyin: "xìng", french: "surname" },
{ chinese: "问题", pinyin: "wèntí", french: "question" },
{ chinese: "事情", pinyin: "shìqing", french: "thing" },
{ chinese: "考试", pinyin: "kǎoshì", french: "exam" },
{ chinese: "票", pinyin: "piào", french: "ticket" },
{ chinese: "意思", pinyin: "yìsi", french: "meaning" },
{ chinese: "颜色", pinyin: "yánsè", french: "color" },
{ chinese: "铅笔", pinyin: "qiánbǐ", french: "pencil" },
{ chinese: "面条", pinyin: "miàntiáo", french: "noodles" },
{ chinese: "火车站", pinyin: "huǒchēzhàn", french: "train station" },
{ chinese: "公司", pinyin: "gōngsī", french: "company" },
{ chinese: "宾馆", pinyin: "bīngguǎn", french: "hotel" },
{ chinese: "说话", pinyin: "shuōhuà", french: "speak" },
{ chinese: "卖", pinyin: "mài", french: "sell" },
{ chinese: "问", pinyin: "wèn", french: "ask" },
{ chinese: "走", pinyin: "zǒu", french: "walk" },
{ chinese: "进", pinyin: "jìn", french: "enter" },
{ chinese: "出", pinyin: "chū", french: "exit" },
{ chinese: "跑步", pinyin: "pǎobù", french: "run" },
{ chinese: "到", pinyin: "dào", french: "arrive" },
{ chinese: "穿", pinyin: "chuān", french: "wear" },
{ chinese: "洗", pinyin: "xǐ", french: "wash" },
{ chinese: "给", pinyin: "gěi", french: "give" },
{ chinese: "找", pinyin: "zhǎo", french: "find" },
{ chinese: "懂", pinyin: "dǒng", french: "understand" },
{ chinese: "笑", pinyin: "xiào", french: "smile" },
{ chinese: "告诉", pinyin: "gàosù", french: "tell" },
{ chinese: "准备", pinyin: "zhǔnbèi", french: "prepare" },
{ chinese: "开始", pinyin: "kāishǐ", french: "start" },
{ chinese: "介绍", pinyin: "jièshào", french: "introduce" },
{ chinese: "帮助", pinyin: "bāngzhù", french: "help" },
{ chinese: "玩", pinyin: "wán", french: "play" },
{ chinese: "送", pinyin: "sòng", french: "give (as a gift)" },
{ chinese: "等", pinyin: "děng", french: "wait" },
{ chinese: "让", pinyin: "ràng", french: "let" },
{ chinese: "起床", pinyin: "qǐchuáng", french: "get up" },
{ chinese: "唱歌", pinyin: "chànggē", french: "sing" },
{ chinese: "跳舞", pinyin: "tiàowǔ", french: "dance" },
{ chinese: "旅游", pinyin: "lǚyóu", french: "travel" },
{ chinese: "上班", pinyin: "shàngbān", french: "go to work" },
{ chinese: "生病", pinyin: "shēngbìng", french: "get sick" },
{ chinese: "休息", pinyin: "xiūxi", french: "rest" },
{ chinese: "运动", pinyin: "yùndòng", french: "exercise" },
{ chinese: "游泳", pinyin: "yóuyǒng", french: "swim" },
{ chinese: "踢足球", pinyin: "tīzúqiú", french: "play football" },
{ chinese: "打篮球", pinyin: "dǎlánqiú", french: "play basketball" },
{ chinese: "完", pinyin: "wán", french: "finish" },
{ chinese: "觉得", pinyin: "juéde", french: "think" },
{ chinese: "知道", pinyin: "zhīdao", french: "know" },
{ chinese: "希望", pinyin: "xīwàng", french: "hope" },
{ chinese: "可以", pinyin: "kěyǐ", french: "can" },
{ chinese: "要", pinyin: "yào", french: "want" },
{ chinese: "可能", pinyin: "kěnéng", french: "maybe" },
{ chinese: "高", pinyin: "gāo", french: "tall" },
{ chinese: "红", pinyin: "hóng", french: "red" },
{ chinese: "白", pinyin: "bái", french: "white" },
{ chinese: "黑", pinyin: "hēi", french: "black" },
{ chinese: "忙", pinyin: "máng", french: "busy" },
{ chinese: "快", pinyin: "kuài", french: "fast" },
{ chinese: "慢", pinyin: "màn", french: "slow" },
{ chinese: "远", pinyin: "yuǎn", french: "far" },
{ chinese: "近", pinyin: "jìn", french: "near" },
{ chinese: "好吃", pinyin: "hǎochī", french: "delicious" },
{ chinese: "累", pinyin: "lèi", french: "tired" },
{ chinese: "长", pinyin: "cháng", french: "long" },
{ chinese: "新", pinyin: "xīn", french: "new" },
{ chinese: "贵", pinyin: "guì", french: "expensive" },
{ chinese: "便宜", pinyin: "piányi", french: "cheap" },
{ chinese: "晴", pinyin: "qíng", french: "sunny" },
{ chinese: "阴", pinyin: "yīn", french: "cloudy" },
{ chinese: "错", pinyin: "cuò", french: "wrong" },
{ chinese: "快乐", pinyin: "kuàilè", french: "happy" },
{ chinese: "对", pinyin: "duì", french: "correct" },
{ chinese: "对", pinyin: "duì", french: "towards" }
];


