 var title = "HSK 2"
 var date = "2025-10-29"

 var flashcards = [
{ chinese: "您", pinyin: "nín", french: "vous (formel)" },
{ chinese: "它", pinyin: "tā", french: "il, elle (pour les objets et animaux)" },
{ chinese: "大家", pinyin: "dàjiā", french: "tout le monde" },
{ chinese: "每", pinyin: "měi", french: "chaque" },
{ chinese: "为什么", pinyin: "wèishénme", french: "pourquoi" },
{ chinese: "零", pinyin: "líng", french: "zéro" },
{ chinese: "两", pinyin: "liǎng", french: "deux" },
{ chinese: "百", pinyin: "bǎi", french: "cent" },
{ chinese: "千", pinyin: "qiān", french: "mille" },
{ chinese: "第一", pinyin: "dìyī", french: "premier" },
{ chinese: "次", pinyin: "cì", french: "fois" },
{ chinese: "件", pinyin: "jiàn", french: "pièce, article" },
{ chinese: "别", pinyin: "bié", french: "ne... pas" },
{ chinese: "非常", pinyin: "fēicháng", french: "très" },
{ chinese: "也", pinyin: "yě", french: "aussi" },
{ chinese: "还", pinyin: "hái", french: "encore" },
{ chinese: "最", pinyin: "zuì", french: "le plus" },
{ chinese: "真", pinyin: "zhēn", french: "vraiment" },
{ chinese: "正在", pinyin: "zhèngzài", french: "en train de" },
{ chinese: "已经", pinyin: "yǐjīng", french: "déjà" },
{ chinese: "一起", pinyin: "yìqǐ", french: "ensemble" },
{ chinese: "再", pinyin: "zài", french: "encore" },
{ chinese: "就", pinyin: "jiù", french: "alors, justement" },
{ chinese: "因为……所以……", pinyin: "yīnwèi…suǒyǐ…", french: "parce que... donc..." },
{ chinese: "虽然……但是……", pinyin: "suīrán…dànshì…", french: "bien que... mais..." },
{ chinese: "从", pinyin: "cóng", french: "de, depuis" },
{ chinese: "比", pinyin: "bǐ", french: "comparer à" },
{ chinese: "往", pinyin: "wǎng", french: "vers" },
{ chinese: "离", pinyin: "lí", french: "à (distance de)" },
{ chinese: "得", pinyin: "de", french: "particule structurale" },
{ chinese: "着", pinyin: "zhe", french: "particule aspectuelle" },
{ chinese: "过", pinyin: "guò", french: "particule aspectuelle" },
{ chinese: "吧", pinyin: "ba", french: "particule modale (suggestion)" },
{ chinese: "机场", pinyin: "jīchǎng", french: "aéroport" },
{ chinese: "教室", pinyin: "jiàoshì", french: "salle de classe" },
{ chinese: "房间", pinyin: "fángjiān", french: "chambre" },
{ chinese: "路", pinyin: "lù", french: "route" },
{ chinese: "左边", pinyin: "zuǒbiān", french: "gauche (côté)" },
{ chinese: "右边", pinyin: "yòubiān", french: "droite (côté)" },
{ chinese: "外", pinyin: "wài", french: "dehors" },
{ chinese: "旁边", pinyin: "pángbiān", french: "à côté de" },
{ chinese: "一下", pinyin: "yīxià", french: "un instant" },
{ chinese: "早上", pinyin: "zǎoshàng", french: "matin" },
{ chinese: "晚上", pinyin: "wǎnshàng", french: "soir" },
{ chinese: "小时", pinyin: "xiǎoshí", french: "heure" },
{ chinese: "时间", pinyin: "shíjiān", french: "temps" },
{ chinese: "去年", pinyin: "qùnián", french: "l'année dernière" },
{ chinese: "日", pinyin: "rì", french: "jour" },
{ chinese: "生日", pinyin: "shēngrì", french: "anniversaire" },
{ chinese: "哥哥", pinyin: "gēge", french: "frère aîné" },
{ chinese: "姐姐", pinyin: "jiějie", french: "sœur aînée" },
{ chinese: "弟弟", pinyin: "dìdi", french: "frère cadet" },
{ chinese: "妹妹", pinyin: "mèimei", french: "sœur cadette" },
{ chinese: "丈夫", pinyin: "zhàngfu", french: "mari" },
{ chinese: "妻子", pinyin: "qīzi", french: "femme" },
{ chinese: "孩子", pinyin: "háizi", french: "enfant" },
{ chinese: "男人", pinyin: "nánrén", french: "homme" },
{ chinese: "女人", pinyin: "nǚrén", french: "femme" },
{ chinese: "服务员", pinyin: "fúwùyuán", french: "serveur/serveuse" },
{ chinese: "鱼", pinyin: "yú", french: "poisson" },
{ chinese: "羊肉", pinyin: "yángròu", french: "mouton (viande)" },
{ chinese: "牛奶", pinyin: "niúnǎi", french: "lait" },
{ chinese: "鸡蛋", pinyin: "jīdàn", french: "œuf" },
{ chinese: "西瓜", pinyin: "xīguā", french: "pastèque" },
{ chinese: "咖啡", pinyin: "kāfēi", french: "café" },
{ chinese: "雪", pinyin: "xuě", french: "neige" },
{ chinese: "药", pinyin: "yào", french: "médicament" },
{ chinese: "手机", pinyin: "shǒujī", french: "téléphone portable" },
{ chinese: "手表", pinyin: "shǒubiǎo", french: "montre" },
{ chinese: "眼睛", pinyin: "yǎnjīng", french: "œil" },
{ chinese: "身体", pinyin: "shēntǐ", french: "corps" },
{ chinese: "公共汽车", pinyin: "gōnggòngqìchē", french: "bus" },
{ chinese: "报纸", pinyin: "bàozhǐ", french: "journal" },
{ chinese: "门", pinyin: "mén", french: "porte" },
{ chinese: "题", pinyin: "tí", french: "question, problème" },
{ chinese: "课", pinyin: "kè", french: "cours, leçon" },
{ chinese: "姓", pinyin: "xìng", french: "nom de famille" },
{ chinese: "问题", pinyin: "wèntí", french: "question, problème" },
{ chinese: "事情", pinyin: "shìqing", french: "chose, affaire" },
{ chinese: "考试", pinyin: "kǎoshì", french: "examen" },
{ chinese: "票", pinyin: "piào", french: "billet" },
{ chinese: "意思", pinyin: "yìsi", french: "sens, signification" },
{ chinese: "颜色", pinyin: "yánsè", french: "couleur" },
{ chinese: "铅笔", pinyin: "qiánbǐ", french: "crayon" },
{ chinese: "面条", pinyin: "miàntiáo", french: "nouilles" },
{ chinese: "火车站", pinyin: "huǒchēzhàn", french: "gare" },
{ chinese: "公司", pinyin: "gōngsī", french: "entreprise" },
{ chinese: "宾馆", pinyin: "bīngguǎn", french: "hôtel" },
{ chinese: "说话", pinyin: "shuōhuà", french: "parler" },
{ chinese: "卖", pinyin: "mài", french: "vendre" },
{ chinese: "问", pinyin: "wèn", french: "demander" },
{ chinese: "走", pinyin: "zǒu", french: "marcher" },
{ chinese: "进", pinyin: "jìn", french: "entrer" },
{ chinese: "出", pinyin: "chū", french: "sortir" },
{ chinese: "跑步", pinyin: "pǎobù", french: "courir" },
{ chinese: "到", pinyin: "dào", french: "arriver" },
{ chinese: "穿", pinyin: "chuān", french: "porter (vêtement)" },
{ chinese: "洗", pinyin: "xǐ", french: "laver" },
{ chinese: "给", pinyin: "gěi", french: "donner" },
{ chinese: "找", pinyin: "zhǎo", french: "chercher" },
{ chinese: "懂", pinyin: "dǒng", french: "comprendre" },
{ chinese: "笑", pinyin: "xiào", french: "rire" },
{ chinese: "告诉", pinyin: "gàosù", french: "dire, informer" },
{ chinese: "准备", pinyin: "zhǔnbèi", french: "préparer" },
{ chinese: "开始", pinyin: "kāishǐ", french: "commencer" },
{ chinese: "介绍", pinyin: "jièshào", french: "présenter" },
{ chinese: "帮助", pinyin: "bāngzhù", french: "aider" },
{ chinese: "玩", pinyin: "wán", french: "jouer, s'amuser" },
{ chinese: "送", pinyin: "sòng", french: "offrir, accompagner" },
{ chinese: "等", pinyin: "děng", french: "attendre" },
{ chinese: "让", pinyin: "ràng", french: "laisser, permettre" },
{ chinese: "起床", pinyin: "qǐchuáng", french: "se lever" },
{ chinese: "唱歌", pinyin: "chànggē", french: "chanter" },
{ chinese: "跳舞", pinyin: "tiàowǔ", french: "danser" },
{ chinese: "旅游", pinyin: "lǚyóu", french: "voyager" },
{ chinese: "上班", pinyin: "shàngbān", french: "aller au travail" },
{ chinese: "生病", pinyin: "shēngbìng", french: "tomber malade" },
{ chinese: "休息", pinyin: "xiūxi", french: "se reposer" },
{ chinese: "运动", pinyin: "yùndòng", french: "faire du sport" },
{ chinese: "游泳", pinyin: "yóuyǒng", french: "nager" },
{ chinese: "踢足球", pinyin: "tīzúqiú", french: "jouer au football" },
{ chinese: "打篮球", pinyin: "dǎlánqiú", french: "jouer au basket-ball" },
{ chinese: "完", pinyin: "wán", french: "finir" },
{ chinese: "觉得", pinyin: "juédé", french: "penser, trouver" },
{ chinese: "知道", pinyin: "zhīdao", french: "savoir" },
{ chinese: "希望", pinyin: "xīwàng", french: "espérer" },
{ chinese: "可以", pinyin: "kěyǐ", french: "pouvoir" },
{ chinese: "要", pinyin: "yào", french: "vouloir, devoir" },
{ chinese: "可能", pinyin: "kěnéng", french: "peut-être" },
{ chinese: "高", pinyin: "gāo", french: "grand, haut" },
{ chinese: "红", pinyin: "hóng", french: "rouge" },
{ chinese: "白", pinyin: "bái", french: "blanc" },
{ chinese: "黑", pinyin: "hēi", french: "noir" },
{ chinese: "忙", pinyin: "máng", french: "occupé" },
{ chinese: "快", pinyin: "kuài", french: "rapide" },
{ chinese: "慢", pinyin: "màn", french: "lent" },
{ chinese: "远", pinyin: "yuǎn", french: "loin" },
{ chinese: "近", pinyin: "jìn", french: "près" },
{ chinese: "好吃", pinyin: "hǎochī", french: "délicieux" },
{ chinese: "累", pinyin: "lèi", french: "fatigué" },
{ chinese: "长", pinyin: "cháng", french: "long" },
{ chinese: "新", pinyin: "xīn", french: "nouveau" },
{ chinese: "贵", pinyin: "guì", french: "cher (prix)" },
{ chinese: "便宜", pinyin: "piányi", french: "bon marché" },
{ chinese: "晴", pinyin: "qíng", french: "ensoleillé" },
{ chinese: "阴", pinyin: "yīn", french: "nuageux" },
{ chinese: "错", pinyin: "cuò", french: "faux" },
{ chinese: "快乐", pinyin: "kuàilè", french: "joyeux" },
{ chinese: "对", pinyin: "duì", french: "correct" },
{ chinese: "对", pinyin: "duì", french: "juste" }
];
