export var title = "HSK 3"
export var date = "2025-10-30"

export var flashcards = [
{chinese: "阿姨", pinyin: "āyí", english: "aunt"},
{chinese: "啊", pinyin: "a", english: "ah"},
{chinese: "矮", pinyin: "ǎi", english: "short"},
{chinese: "爱好", pinyin: "àihào", english: "hobby"},
{chinese: "安静", pinyin: "ānjìng", english: "be quiet"},
{chinese: "把", pinyin: "bǎ", english: "hold"},
{chinese: "班", pinyin: "bān", english: "class"},
{chinese: "搬", pinyin: "bān", english: "move"},
{chinese: "半", pinyin: "bàn", english: "half"},
{chinese: "办法", pinyin: "bànfǎ", english: "way"},
{chinese: "办公室", pinyin: "bàngōngshì", english: "office"},
{chinese: "帮忙", pinyin: "bāngmáng", english: "help"},
{chinese: "包", pinyin: "bāo", english: "package"},
{chinese: "饱", pinyin: "bǎo", english: "full"},
{chinese: "北方", pinyin: "běifāng", english: "north"},
{chinese: "被", pinyin: "bèi", english: "cover"},
{chinese: "鼻子", pinyin: "bízi", english: "nose"},
{chinese: "比较", pinyin: "bǐjiào", english: "compare"},
{chinese: "比赛", pinyin: "bǐsài", english: "match"},
{chinese: "笔记本", pinyin: "bǐjìběn", english: "notebook"},
{chinese: "必须", pinyin: "bìxū", english: "must"},
{chinese: "变化", pinyin: "biànhuà", english: "change"},
{chinese: "别人", pinyin: "biéren", english: "others"},
{chinese: "冰箱", pinyin: "bīngxiāng", english: "refrigerator"},
{chinese: "菜单", pinyin: "càidān", english: "menu"},
{chinese: "参加", pinyin: "cānjiā", english: "participate in"},
{chinese: "草", pinyin: "cǎo", english: "grass"},
{chinese: "层", pinyin: "céng", english: "layer"},
{chinese: "差", pinyin: "chà", english: "bad"},
{chinese: "超市", pinyin: "chāoshì", english: "supermarket"},
{chinese: "衬衫", pinyin: "chènshān", english: "shirt"},
{chinese: "成绩", pinyin: "chéngjì", english: "achievement"},
{chinese: "城市", pinyin: "chéngshì", english: "city"},
{chinese: "迟到", pinyin: "chídào", english: "late"},
{chinese: "除了", pinyin: "chúle", english: "except, besides"},
{chinese: "船", pinyin: "chuán", english: "ship"},
{chinese: "春", pinyin: "chūn", english: "spring"},
{chinese: "词典", pinyin: "cídiǎn", english: "dictionaries"},
{chinese: "聪明", pinyin: "cōngming", english: "clever"},
{chinese: "打扫", pinyin: "dǎsǎo", english: "clean"},
{chinese: "打算", pinyin: "dǎsuàn", english: "plan"},
{chinese: "带", pinyin: "dài", english: "belt"},
{chinese: "担心", pinyin: "dānxīn", english: "worry"},
{chinese: "蛋糕", pinyin: "dàngāo", english: "cake"},
{chinese: "当然", pinyin: "dāngrán", english: "of course"},
{chinese: "地", pinyin: "de", english: ""},
{chinese: "灯", pinyin: "dēng", english: "lamp"},
{chinese: "地方", pinyin: "dìfang", english: "local"},
{chinese: "地铁", pinyin: "dìtiě", english: "metro"},
{chinese: "地图", pinyin: "dìtú", english: "map"},
{chinese: "电梯", pinyin: "diàntī", english: "elevator"},
{chinese: "电子邮件", pinyin: "diànzǐyóujiàn", english: "e-mail"},
{chinese: "东", pinyin: "dōng", english: "east"},
{chinese: "冬", pinyin: "dōng", english: "winter"},
{chinese: "动物", pinyin: "dòngwù", english: "animal"},
{chinese: "短", pinyin: "duǎn", english: "short"},
{chinese: "段", pinyin: "duàn", english: "paragraph"},
{chinese: "锻炼", pinyin: "duànliàn", english: "physical exercise"},
{chinese: "多么", pinyin: "duōme", english: "such"},
{chinese: "饿", pinyin: "è", english: "hungry"},
{chinese: "不但……而且……", pinyin: "búdàn…érqiě…", english: "not only…but also…"},
{chinese: "耳朵", pinyin: "ěrduo", english: "ears"},
{chinese: "发", pinyin: "fā", english: "send out"},
{chinese: "发烧", pinyin: "fāshāo", english: "have a fever"},
{chinese: "发现", pinyin: "fāxiàn", english: "find, discover"},
{chinese: "方便", pinyin: "fāngbiàn", english: "convenient"},
{chinese: "放", pinyin: "fàng", english: "discharge"},
{chinese: "放心", pinyin: "fàngxīn", english: "don’t worry"},
{chinese: "分", pinyin: "fēn", english: "minute"},
{chinese: "附近", pinyin: "fùjìn", english: "nearby"},
{chinese: "复习", pinyin: "fùxí", english: "review"},
{chinese: "干净", pinyin: "gānjìng", english: "clean"},
{chinese: "感兴趣", pinyin: "gǎnxìngqù", english: "be interested in"},
{chinese: "感冒", pinyin: "gǎnmào", english: "get a cold"},
{chinese: "刚才", pinyin: "gāngcái", english: "just"},
{chinese: "个子", pinyin: "gèzi", english: "height"},
{chinese: "跟", pinyin: "gēn", english: "with"},
{chinese: "根据", pinyin: "gēnjù", english: "according to"},
{chinese: "更", pinyin: "gèng", english: "more"},
{chinese: "公斤", pinyin: "gōngjīn", english: "kg."},
{chinese: "公园", pinyin: "gōngyuán", english: "park"},
{chinese: "故事", pinyin: "gùshi", english: "story"},
{chinese: "刮风", pinyin: "guāfēng", english: "windy"},
{chinese: "关", pinyin: "guān", english: "shut"},
{chinese: "关系", pinyin: "guānxì", english: "relationship"},
{chinese: "关心", pinyin: "guānxīn", english: "care for"},
{chinese: "关于", pinyin: "guānyú", english: "about"},
{chinese: "国家", pinyin: "guójiā", english: "country"},
{chinese: "过去", pinyin: "guòqù", english: "past times"},
{chinese: "过（动词）", pinyin: "guò", english: "pass"},
{chinese: "还是", pinyin: "háishì", english: "still"},
{chinese: "害怕", pinyin: "hàipà", english: "fear"},
{chinese: "黑板", pinyin: "hēibǎn", english: "blackboard"},
{chinese: "后来", pinyin: "hòulái", english: "later"},
{chinese: "护照", pinyin: "hùzhào", english: "passport"},
{chinese: "花（动词）", pinyin: "huā", english: "spend"},
{chinese: "花（名词）", pinyin: "huā", english: "flower"},
{chinese: "画", pinyin: "huà", english: "painting"},
{chinese: "坏", pinyin: "huài", english: "bad"},
{chinese: "欢迎", pinyin: "huānyíng", english: "welcome"},
{chinese: "还（动词）", pinyin: "huán", english: "return"},
{chinese: "环境", pinyin: "huánjìng", english: "environment"},
{chinese: "换", pinyin: "huàn", english: "change"},
{chinese: "黄河", pinyin: "huánghé", english: "yellow river"},
{chinese: "回答", pinyin: "huídá", english: "answer"},
{chinese: "会议", pinyin: "huìyì", english: "meeting"},
{chinese: "或者", pinyin: "huòzhě", english: "perhaps"},
{chinese: "几乎", pinyin: "jīhū", english: "almost"},
{chinese: "机会", pinyin: "jīhuì", english: "opportunity"},
{chinese: "极", pinyin: "jí", english: "extremely"},
{chinese: "记得", pinyin: "jìde", english: "remember"},
{chinese: "季节", pinyin: "jìjié", english: "season"},
{chinese: "检查", pinyin: "jiǎnchá", english: "inspect"},
{chinese: "简单", pinyin: "jiǎndān", english: "simple"},
{chinese: "健康", pinyin: "jiànkāng", english: "healthy"},
{chinese: "见面", pinyin: "jiànmiàn", english: "meet"},
{chinese: "讲", pinyin: "jiǎng", english: "speak"},
{chinese: "教", pinyin: "jiāo", english: "teach"},
{chinese: "角", pinyin: "jiǎo", english: "horn"},
{chinese: "脚", pinyin: "jiǎo", english: "foot"},
{chinese: "接", pinyin: "jiē", english: "pick, get"},
{chinese: "街道", pinyin: "jiēdào", english: "street"},
{chinese: "结婚", pinyin: "jiéhūn", english: "marry"},
{chinese: "结束", pinyin: "jiéshù", english: "end"},
{chinese: "节目", pinyin: "jiémù", english: "program"},
{chinese: "节日", pinyin: "jiérì", english: "festival"},
{chinese: "解决", pinyin: "jiějué", english: "solve"},
{chinese: "借", pinyin: "jiè", english: "borrow"},
{chinese: "经常", pinyin: "jīngcháng", english: "often"},
{chinese: "经过", pinyin: "jīngguò", english: "after, through"},
{chinese: "经理", pinyin: "jīnglǐ", english: "manager"},
{chinese: "久", pinyin: "jiǔ", english: "long"},
{chinese: "旧", pinyin: "jiù", english: "old, used"},
{chinese: "句子", pinyin: "jùzi", english: "sentence"},
{chinese: "决定", pinyin: "juédìng", english: "decision"},
{chinese: "渴", pinyin: "kě", english: "thirsty"},
{chinese: "可爱", pinyin: "kě’ài", english: "lovely"},
{chinese: "刻", pinyin: "kè", english: "moment"},
{chinese: "客人", pinyin: "kèrén", english: "guest"},
{chinese: "空调", pinyin: "kōngtiáo", english: "air conditioner"},
{chinese: "口", pinyin: "kǒu", english: "mouth"},
{chinese: "哭", pinyin: "kū", english: "cry"},
{chinese: "裤子", pinyin: "kùzi", english: "trousers"},
{chinese: "筷子", pinyin: "kuàizi", english: "chopsticks"},
{chinese: "蓝", pinyin: "lán", english: "blue"},
{chinese: "老", pinyin: "lǎo", english: "old"},
{chinese: "离开", pinyin: "líkāi", english: "leave"},
{chinese: "礼物", pinyin: "lǐwù", english: "gift"},
{chinese: "历史", pinyin: "lìshǐ", english: "history"},
{chinese: "脸", pinyin: "liǎn", english: "face"},
{chinese: "聊天", pinyin: "liáotiān", english: "chat"},
{chinese: "练习", pinyin: "liànxí", english: "practice"},
{chinese: "辆", pinyin: "liàng", english: "car"},
{chinese: "了解", pinyin: "liǎojiě", english: "understand"},
{chinese: "邻居", pinyin: "línjū", english: "neighbor"},
{chinese: "留学", pinyin: "liúxué", english: "overseas study"},
{chinese: "楼", pinyin: "lóu", english: "floor"},
{chinese: "绿", pinyin: "lǜ", english: "green"},
{chinese: "马", pinyin: "mǎ", english: "horse"},
{chinese: "马上", pinyin: "mǎshàng", english: "right off"},
{chinese: "满意", pinyin: "mǎnyì", english: "satisfied"},
{chinese: "帽子", pinyin: "màozi", english: "hat"},
{chinese: "米", pinyin: "mǐ", english: "rice"},
{chinese: "面包", pinyin: "miànbāo", english: "bread"},
{chinese: "明白", pinyin: "míngbai", english: "clear"},
{chinese: "拿", pinyin: "ná", english: "take"},
{chinese: "奶奶", pinyin: "nǎinai", english: "grandma"},
{chinese: "南", pinyin: "nán", english: "south"},
{chinese: "难", pinyin: "nán", english: "difficult"},
{chinese: "难过", pinyin: "nánguò", english: "sad"},
{chinese: "年级", pinyin: "niánjí", english: "grade"},
{chinese: "年轻", pinyin: "niánqīng", english: "young"},
{chinese: "鸟", pinyin: "niǎo", english: "bird"},
{chinese: "努力", pinyin: "nǔlì", english: "strive"},
{chinese: "爬山", pinyin: "páshān", english: "mountain climbing"},
{chinese: "盘子", pinyin: "pánzi", english: "plate"},
{chinese: "胖", pinyin: "pàng", english: "fat"},
{chinese: "啤酒", pinyin: "píjiǔ", english: "beer"},
{chinese: "皮鞋", pinyin: "píxié", english: "leather shoes"},
{chinese: "瓶子", pinyin: "píngzi", english: "bottle"},
{chinese: "其实", pinyin: "qíshí", english: "actually"},
{chinese: "其他", pinyin: "qítā", english: "other"},
{chinese: "骑", pinyin: "qí", english: "ride"},
{chinese: "奇怪", pinyin: "qíguài", english: "strange"},
{chinese: "起来", pinyin: "qǐlái", english: "get up"},
{chinese: "起飞", pinyin: "qǐfēi", english: "take off"},
{chinese: "清楚", pinyin: "qīngchu", english: "clear"},
{chinese: "请假", pinyin: "qǐngjià", english: "ask for leave"},
{chinese: "秋", pinyin: "qiū", english: "autumn"},
{chinese: "裙子", pinyin: "qúnzi", english: "skirt"},
{chinese: "然后", pinyin: "ránhòu", english: "then"},
{chinese: "热情", pinyin: "rèqíng", english: "enthusiasm"},
{chinese: "认为", pinyin: "rènwéi", english: "think"},
{chinese: "认真", pinyin: "rènzhēn", english: "earnest"},
{chinese: "容易", pinyin: "róngyì", english: "easily"},
{chinese: "如果", pinyin: "rúguǒ", english: "if"},
{chinese: "伞", pinyin: "sǎn", english: "umbrella"},
{chinese: "上网", pinyin: "shàngwǎng", english: "surf the internet"},
{chinese: "生气", pinyin: "shēngqì", english: "get angry"},
{chinese: "声音", pinyin: "shēngyīn", english: "voice"},
{chinese: "试", pinyin: "shì", english: "try"},
{chinese: "世界", pinyin: "shìjiè", english: "world"},
{chinese: "瘦", pinyin: "shòu", english: "thin"},
{chinese: "舒服", pinyin: "shūfu", english: "comfortable"},
{chinese: "叔叔", pinyin: "shūshu", english: "uncle"},
{chinese: "树", pinyin: "shù", english: "tree"},
{chinese: "数学", pinyin: "shùxué", english: "mathematics"},
{chinese: "刷牙", pinyin: "shuāyá", english: "brush one’s teeth"},
{chinese: "双", pinyin: "shuāng", english: "double, pair"},
{chinese: "水平", pinyin: "shuǐpíng", english: "level"},
{chinese: "司机", pinyin: "sījī", english: "driver"},
{chinese: "太阳", pinyin: "tàiyáng", english: "sun"},
{chinese: "特别", pinyin: "tèbié", english: "especially"},
{chinese: "疼", pinyin: "téng", english: "hurt"},
{chinese: "提高", pinyin: "tígāo", english: "increase"},
{chinese: "体育", pinyin: "tǐyù", english: "sports"},
{chinese: "甜", pinyin: "tián", english: "sweet"},
{chinese: "条", pinyin: "tiáo", english: "strip"},
{chinese: "同事", pinyin: "tóngshì", english: "colleague"},
{chinese: "同意", pinyin: "tóngyì", english: "agree"},
{chinese: "头发", pinyin: "tóufa", english: "hair"},
{chinese: "突然", pinyin: "tūrán", english: "suddenly"},
{chinese: "图书馆", pinyin: "túshūguǎn", english: "library"},
{chinese: "腿", pinyin: "tuǐ", english: "leg"},
{chinese: "完成", pinyin: "wánchéng", english: "complete"},
{chinese: "碗", pinyin: "wǎn", english: "bowl"},
{chinese: "万", pinyin: "wàn", english: "ten thousand"},
{chinese: "忘记", pinyin: "wàngjì", english: "forget"},
{chinese: "为", pinyin: "wèi", english: "for"},
{chinese: "为了", pinyin: "wèile", english: "in order to"},
{chinese: "位", pinyin: "wèi", english: "position"},
{chinese: "文化", pinyin: "wénhuà", english: "culture"},
{chinese: "西", pinyin: "xī", english: "west"},
{chinese: "习惯", pinyin: "xíguàn", english: "habit"},
{chinese: "洗手间", pinyin: "xǐshǒujiān", english: "restroom"},
{chinese: "洗澡", pinyin: "xǐzǎo", english: "take a shower"},
{chinese: "夏", pinyin: "xià", english: "summer"},
{chinese: "先", pinyin: "xiān", english: "first"},
{chinese: "香蕉", pinyin: "xiāngjiāo", english: "banana"},
{chinese: "相信", pinyin: "xiāngxìn", english: "believe"},
{chinese: "向", pinyin: "xiàng", english: "towards"},
{chinese: "像", pinyin: "xiàng", english: "image"},
{chinese: "小心", pinyin: "xiǎoxīn", english: "watch out"},
{chinese: "校长", pinyin: "xiàozhǎng", english: "principal"},
{chinese: "新闻", pinyin: "xīnwén", english: "news"},
{chinese: "新鲜", pinyin: "xīnxiān", english: "fresh"},
{chinese: "信用卡", pinyin: "xìnyòngkǎ", english: "credit card"},
{chinese: "行李箱", pinyin: "xínglixiāng", english: "trunk"},
{chinese: "熊猫", pinyin: "xióngmāo", english: "panda"},
{chinese: "需要", pinyin: "xūyào", english: "need"},
{chinese: "选择", pinyin: "xuǎnzé", english: "choice"},
{chinese: "要求", pinyin: "yāoqiú", english: "requirement"},
{chinese: "爷爷", pinyin: "yéye", english: "grandpa"},
{chinese: "一定", pinyin: "yídìng", english: "certain"},
{chinese: "一共", pinyin: "yígòng", english: "altogether"},
{chinese: "一会儿", pinyin: "yíhuìr", english: "a while"},
{chinese: "一样", pinyin: "yíyàng", english: "equally"},
{chinese: "以前", pinyin: "yǐqián", english: "before"},
{chinese: "一般", pinyin: "yìbān", english: "commonly"},
{chinese: "一边", pinyin: "yìbiān", english: "one side"},
{chinese: "一直", pinyin: "yìzhí", english: "always"},
{chinese: "音乐", pinyin: "yīnyuè", english: "music"},
{chinese: "银行", pinyin: "yínháng", english: "bank"},
{chinese: "饮料", pinyin: "yǐnliào", english: "drinks"},
{chinese: "应该", pinyin: "yīnggāi", english: "should"},
{chinese: "影响", pinyin: "yǐngxiǎng", english: "influence"},
{chinese: "用", pinyin: "yòng", english: "use"},
{chinese: "游戏", pinyin: "yóuxì", english: "game"},
{chinese: "有名", pinyin: "yǒumíng", english: "famous"},
{chinese: "又", pinyin: "yòu", english: "again"},
{chinese: "遇到", pinyin: "yùdào", english: "encounter"},
{chinese: "元", pinyin: "yuán", english: "element; yuan"},
{chinese: "愿意", pinyin: "yuànyì", english: "be willing"},
{chinese: "月亮", pinyin: "yuèliang", english: "moon"},
{chinese: "越", pinyin: "yuè", english: "the more"},
{chinese: "站", pinyin: "zhàn", english: "station"},
{chinese: "张", pinyin: "zhāng", english: "zhang (surname)"},
{chinese: "长（动词）", pinyin: "zhǎng", english: "grow"},
{chinese: "着急", pinyin: "zháojí", english: "worry"},
{chinese: "照顾", pinyin: "zhàogù", english: "look after"},
{chinese: "照片", pinyin: "zhàopiàn", english: "photo"},
{chinese: "照相机", pinyin: "zhàoxiàngjī", english: "camera"},
{chinese: "只（量词）", pinyin: "zhī", english: "(measure word)"},
{chinese: "只（副词）", pinyin: "zhǐ", english: "only"},
{chinese: "只有……才……", pinyin: "zhǐyǒu…cái…", english: "only if"},
{chinese: "中文", pinyin: "zhōngwén", english: "chinese"},
{chinese: "中间", pinyin: "zhōngjiān", english: "middle"},
{chinese: "终于", pinyin: "zhōngyú", english: "finally"},
{chinese: "种", pinyin: "zhǒng", english: "species"},
{chinese: "重要", pinyin: "zhòngyào", english: "important"},
{chinese: "周末", pinyin: "zhōumò", english: "weekend"},
{chinese: "主要", pinyin: "zhǔyào", english: "main"},
{chinese: "注意", pinyin: "zhùyì", english: "be careful"},
{chinese: "自己", pinyin: "zìjǐ", english: "own, self"},
{chinese: "自行车", pinyin: "zìxíngchē", english: "bicycle"},
{chinese: "总是", pinyin: "zǒngshì", english: "always"},
{chinese: "嘴", pinyin: "zuǐ", english: "mouth"},
{chinese: "最后", pinyin: "zuìhòu", english: "last"},
{chinese: "最近", pinyin: "zuìjìn", english: "lately"},
{chinese: "作业", pinyin: "zuòyè", english: "homework"}
];
