export var title = "HSK 3"
export var date = "2025-10-30"

export var flashcards = [
{chinese: "阿姨", pinyin: "āyí", french: "tante (aunt)"},
{chinese: "啊", pinyin: "a", french: "ah (ah)"},
{chinese: "矮", pinyin: "ǎi", french: "court (short)"},
{chinese: "爱好", pinyin: "àihào", french: "loisir (hobby)"},
{chinese: "安静", pinyin: "ānjìng", french: "être calme (be quiet)"},
{chinese: "把", pinyin: "bǎ", french: "tenir (hold)"},
{chinese: "班", pinyin: "bān", french: "classe (class)"},
{chinese: "搬", pinyin: "bān", french: "déménager (move)"},
{chinese: "半", pinyin: "bàn", french: "moitié (half)"},
{chinese: "办法", pinyin: "bànfǎ", french: "façon (way)"},
{chinese: "办公室", pinyin: "bàngōngshì", french: "bureau (office)"},
{chinese: "帮忙", pinyin: "bāngmáng", french: "aider (help)"},
{chinese: "包", pinyin: "bāo", french: "paquet (package)"},
{chinese: "饱", pinyin: "bǎo", french: "rassasié (full)"},
{chinese: "北方", pinyin: "běifāng", french: "nord (north)"},
{chinese: "被", pinyin: "bèi", french: "couvrir (cover)"},
{chinese: "鼻子", pinyin: "bízi", french: "nez (nose)"},
{chinese: "比较", pinyin: "bǐjiào", french: "comparer (compare)"},
{chinese: "比赛", pinyin: "bǐsài", french: "match (match)"},
{chinese: "笔记本", pinyin: "bǐjìběn", french: "cahier (notebook)"},
{chinese: "必须", pinyin: "bìxū", french: "devoir (must)"},
{chinese: "变化", pinyin: "biànhuà", french: "changement (change)"},
{chinese: "别人", pinyin: "biéren", french: "autres (others)"},
{chinese: "冰箱", pinyin: "bīngxiāng", french: "réfrigérateur (refrigerator)"},
{chinese: "菜单", pinyin: "càidān", french: "menu (menu)"},
{chinese: "参加", pinyin: "cānjiā", french: "participer à (participate in)"},
{chinese: "草", pinyin: "cǎo", french: "herbe (grass)"},
{chinese: "层", pinyin: "céng", french: "couche (layer)"},
{chinese: "差", pinyin: "chà", french: "mauvais (bad)"},
{chinese: "超市", pinyin: "chāoshì", french: "supermarché (supermarket)"},
{chinese: "衬衫", pinyin: "chènshān", french: "chemise (shirt)"},
{chinese: "成绩", pinyin: "chéngjì", french: "succès (achievement)"},
{chinese: "城市", pinyin: "chéngshì", french: "ville (city)"},
{chinese: "迟到", pinyin: "chídào", french: "en retard (late)"},
{chinese: "除了", pinyin: "chúle", french: "sauf, en plus de (except, besides)"},
{chinese: "船", pinyin: "chuán", french: "navire (ship)"},
{chinese: "春", pinyin: "chūn", french: "printemps (spring)"},
{chinese: "词典", pinyin: "cídiǎn", french: "dictionnaires (dictionaries)"},
{chinese: "聪明", pinyin: "cōngming", french: "intelligent (clever)"},
{chinese: "打扫", pinyin: "dǎsǎo", french: "nettoyer (clean)"},
{chinese: "打算", pinyin: "dǎsuàn", french: "planifier (plan)"},
{chinese: "带", pinyin: "dài", french: "ceinture (belt)"},
{chinese: "担心", pinyin: "dānxīn", french: "s'inquiéter (worry)"},
{chinese: "蛋糕", pinyin: "dàngāo", french: "gâteau (cake)"},
{chinese: "当然", pinyin: "dāngrán", french: "bien sûr (of course)"},
{chinese: "地", pinyin: "de", french: ""},
{chinese: "灯", pinyin: "dēng", french: "lampe (lamp)"},
{chinese: "地方", pinyin: "dìfang", french: "local (local)"},
{chinese: "地铁", pinyin: "dìtiě", french: "métro (metro)"},
{chinese: "地图", pinyin: "dìtú", french: "carte (map)"},
{chinese: "电梯", pinyin: "diàntī", french: "ascenseur (elevator)"},
{chinese: "电子邮件", pinyin: "diànzǐyóujiàn", french: "e-mail (e-mail)"},
{chinese: "东", pinyin: "dōng", french: "est (east)"},
{chinese: "冬", pinyin: "dōng", french: "hiver (winter)"},
{chinese: "动物", pinyin: "dòngwù", french: "animal (animal)"},
{chinese: "短", pinyin: "duǎn", french: "court (short)"},
{chinese: "段", pinyin: "duàn", french: "paragraphe (paragraph)"},
{chinese: "锻炼", pinyin: "duànliàn", french: "exercice physique (physical exercise)"},
{chinese: "多么", pinyin: "duōme", french: "tellement (such)"},
{chinese: "饿", pinyin: "è", french: "affamé (hungry)"},
{chinese: "不但……而且……", pinyin: "búdàn…érqiě…", french: "non seulement…mais aussi… (not only…but also…)"},
{chinese: "耳朵", pinyin: "ěrduo", french: "oreilles (ears)"},
{chinese: "发", pinyin: "fā", french: "envoyer (send out)"},
{chinese: "发烧", pinyin: "fāshāo", french: "avoir de la fièvre (have a fever)"},
{chinese: "发现", pinyin: "fāxiàn", french: "trouver, découvrir (find, discover)"},
{chinese: "方便", pinyin: "fāngbiàn", french: "pratique (convenient)"},
{chinese: "放", pinyin: "fàng", french: "décharger (discharge)"},
{chinese: "放心", pinyin: "fàngxīn", french: "ne vous inquiétez pas (don’t worry)"},
{chinese: "分", pinyin: "fēn", french: "minute (minute)"},
{chinese: "附近", pinyin: "fùjìn", french: "à proximité (nearby)"},
{chinese: "复习", pinyin: "fùxí", french: "revoir (review)"},
{chinese: "干净", pinyin: "gānjìng", french: "propre (clean)"},
{chinese: "感兴趣", pinyin: "gǎnxìngqù", french: "être intéressé par (be interested in)"},
{chinese: "感冒", pinyin: "gǎnmào", french: "attraper un rhume (get a cold)"},
{chinese: "刚才", pinyin: "gāngcái", french: "juste (just)"},
{chinese: "个子", pinyin: "gèzi", french: "taille (height)"},
{chinese: "跟", pinyin: "gēn", french: "avec (with)"},
{chinese: "根据", pinyin: "gēnjù", french: "selon (according to)"},
{chinese: "更", pinyin: "gèng", french: "plus (more)"},
{chinese: "公斤", pinyin: "gōngjīn", french: "kg. (kg.)"},
{chinese: "公园", pinyin: "gōngyuán", french: "parc (park)"},
{chinese: "故事", pinyin: "gùshi", french: "histoire (story)"},
{chinese: "刮风", pinyin: "guāfēng", french: "venteux (windy)"},
{chinese: "关", pinyin: "guān", french: "fermer (shut)"},
{chinese: "关系", pinyin: "guānxì", french: "relation (relationship)"},
{chinese: "关心", pinyin: "guānxīn", french: "se soucier de (care for)"},
{chinese: "关于", pinyin: "guānyú", french: "à propos de (about)"},
{chinese: "国家", pinyin: "guójiā", french: "pays (country)"},
{chinese: "过去", pinyin: "guòqù", french: "temps passés (past times)"},
{chinese: "过（动词）", pinyin: "guò", french: "passer (pass)"},
{chinese: "还是", pinyin: "háishì", french: "encore (still)"},
{chinese: "害怕", pinyin: "hàipà", french: "peur (fear)"},
{chinese: "黑板", pinyin: "hēibǎn", french: "tableau noir (blackboard)"},
{chinese: "后来", pinyin: "hòulái", french: "plus tard (later)"},
{chinese: "护照", pinyin: "hùzhào", french: "passeport (passport)"},
{chinese: "花（动词）", pinyin: "huā", french: "dépenser (spend)"},
{chinese: "花（名词）", pinyin: "huā", french: "fleur (flower)"},
{chinese: "画", pinyin: "huà", french: "peinture (painting)"},
{chinese: "坏", pinyin: "huài", french: "mauvais (bad)"},
{chinese: "欢迎", pinyin: "huānyíng", french: "bienvenue (welcome)"},
{chinese: "还（动词）", pinyin: "huán", french: "rendre (return)"},
{chinese: "环境", pinyin: "huánjìng", french: "environnement (environment)"},
{chinese: "换", pinyin: "huàn", french: "changer (change)"},
{chinese: "黄河", pinyin: "huánghé", french: "fleuve jaune (yellow river)"},
{chinese: "回答", pinyin: "huídá", french: "répondre (answer)"},
{chinese: "会议", pinyin: "huìyì", french: "réunion (meeting)"},
{chinese: "或者", pinyin: "huòzhě", french: "peut-être (perhaps)"},
{chinese: "几乎", pinyin: "jīhū", french: "presque (almost)"},
{chinese: "机会", pinyin: "jīhuì", french: "opportunité (opportunity)"},
{chinese: "极", pinyin: "jí", french: "extrêmement (extremely)"},
{chinese: "记得", pinyin: "jìde", french: "se souvenir de (remember)"},
{chinese: "季节", pinyin: "jìjié", french: "saison (season)"},
{chinese: "检查", pinyin: "jiǎnchá", french: "inspecter (inspect)"},
{chinese: "简单", pinyin: "jiǎndān", french: "simple (simple)"},
{chinese: "健康", pinyin: "jiànkāng", french: "sain (healthy)"},
{chinese: "见面", pinyin: "jiànmiàn", french: "rencontrer (meet)"},
{chinese: "讲", pinyin: "jiǎng", french: "parler (speak)"},
{chinese: "教", pinyin: "jiāo", french: "enseigner (teach)"},
{chinese: "角", pinyin: "jiǎo", french: "corne (horn)"},
{chinese: "脚", pinyin: "jiǎo", french: "pied (foot)"},
{chinese: "接", pinyin: "jiē", french: "prendre, obtenir (pick, get)"},
{chinese: "街道", pinyin: "jiēdào", french: "rue (street)"},
{chinese: "结婚", pinyin: "jiéhūn", french: "se marier (marry)"},
{chinese: "结束", pinyin: "jiéshù", french: "fin (end)"},
{chinese: "节目", pinyin: "jiémù", french: "programme (program)"},
{chinese: "节日", pinyin: "jiérì", french: "fête (festival)"},
{chinese: "解决", pinyin: "jiějué", french: "résoudre (solve)"},
{chinese: "借", pinyin: "jiè", french: "emprunter (borrow)"},
{chinese: "经常", pinyin: "jīngcháng", french: "souvent (often)"},
{chinese: "经过", pinyin: "jīngguò", french: "après, à travers (after, through)"},
{chinese: "经理", pinyin: "jīnglǐ", french: "directeur (manager)"},
{chinese: "久", pinyin: "jiǔ", french: "long (long)"},
{chinese: "旧", pinyin: "jiù", french: "vieux, utilisé (old, used)"},
{chinese: "句子", pinyin: "jùzi", french: "phrase (sentence)"},
{chinese: "决定", pinyin: "juédìng", french: "décision (decision)"},
{chinese: "渴", pinyin: "kě", french: "assoiffé (thirsty)"},
{chinese: "可爱", pinyin: "kě’ài", french: "adorable (lovely)"},
{chinese: "刻", pinyin: "kè", french: "moment (moment)"},
{chinese: "客人", pinyin: "kèrén", french: "invité (guest)"},
{chinese: "空调", pinyin: "kōngtiáo", french: "climatiseur (air conditioner)"},
{chinese: "口", pinyin: "kǒu", french: "bouche (mouth)"},
{chinese: "哭", pinyin: "kū", french: "pleurer (cry)"},
{chinese: "裤子", pinyin: "kùzi", french: "pantalon (trousers)"},
{chinese: "筷子", pinyin: "kuàizi", french: "baguettes (chopsticks)"},
{chinese: "蓝", pinyin: "lán", french: "bleu (blue)"},
{chinese: "老", pinyin: "lǎo", french: "vieux (old)"},
{chinese: "离开", pinyin: "líkāi", french: "quitter (leave)"},
{chinese: "礼物", pinyin: "lǐwù", french: "cadeau (gift)"},
{chinese: "历史", pinyin: "lìshǐ", french: "histoire (history)"},
{chinese: "脸", pinyin: "liǎn", french: "visage (face)"},
{chinese: "聊天", pinyin: "liáotiān", french: "discuter (chat)"},
{chinese: "练习", pinyin: "liànxí", french: "pratique (practice)"},
{chinese: "辆", pinyin: "liàng", french: "voiture (car)"},
{chinese: "了解", pinyin: "liǎojiě", french: "comprendre (understand)"},
{chinese: "邻居", pinyin: "línjū", french: "voisin (neighbor)"},
{chinese: "留学", pinyin: "liúxué", french: "études à l'étranger (overseas study)"},
{chinese: "楼", pinyin: "lóu", french: "étage (floor)"},
{chinese: "绿", pinyin: "lǜ", french: "vert (green)"},
{chinese: "马", pinyin: "mǎ", french: "cheval (horse)"},
{chinese: "马上", pinyin: "mǎshàng", french: "tout de suite (right off)"},
{chinese: "满意", pinyin: "mǎnyì", french: "satisfait (satisfied)"},
{chinese: "帽子", pinyin: "màozi", french: "chapeau (hat)"},
{chinese: "米", pinyin: "mǐ", french: "riz (rice)"},
{chinese: "面包", pinyin: "miànbāo", french: "pain (bread)"},
{chinese: "明白", pinyin: "míngbai", french: "clair (clear)"},
{chinese: "拿", pinyin: "ná", french: "prendre (take)"},
{chinese: "奶奶", pinyin: "nǎinai", french: "grand-mère (grandma)"},
{chinese: "南", pinyin: "nán", french: "sud (south)"},
{chinese: "难", pinyin: "nán", french: "difficile (difficult)"},
{chinese: "难过", pinyin: "nánguò", french: "triste (sad)"},
{chinese: "年级", pinyin: "niánjí", french: "année (grade)"},
{chinese: "年轻", pinyin: "niánqīng", french: "jeune (young)"},
{chinese: "鸟", pinyin: "niǎo", french: "oiseau (bird)"},
{chinese: "努力", pinyin: "nǔlì", french: "s'efforcer (strive)"},
{chinese: "爬山", pinyin: "páshān", french: "alpinisme (mountain climbing)"},
{chinese: "盘子", pinyin: "pánzi", french: "assiette (plate)"},
{chinese: "胖", pinyin: "pàng", french: "gros (fat)"},
{chinese: "啤酒", pinyin: "píjiǔ", french: "bière (beer)"},
{chinese: "皮鞋", pinyin: "píxié", french: "chaussures en cuir (leather shoes)"},
{chinese: "瓶子", pinyin: "píngzi", french: "bouteille (bottle)"},
{chinese: "其实", pinyin: "qíshí", french: "en fait (actually)"},
{chinese: "其他", pinyin: "qítā", french: "autre (other)"},
{chinese: "骑", pinyin: "qí", french: "monter (ride)"},
{chinese: "奇怪", pinyin: "qíguài", french: "étrange (strange)"},
{chinese: "起来", pinyin: "qǐlái", french: "se lever (get up)"},
{chinese: "起飞", pinyin: "qǐfēi", french: "décoller (take off)"},
{chinese: "清楚", pinyin: "qīngchu", french: "clair (clear)"},
{chinese: "请假", pinyin: "qǐngjià", french: "demander un congé (ask for leave)"},
{chinese: "秋", pinyin: "qiū", french: "automne (autumn)"},
{chinese: "裙子", pinyin: "qúnzi", french: "jupe (skirt)"},
{chinese: "然后", pinyin: "ránhòu", french: "puis (then)"},
{chinese: "热情", pinyin: "rèqíng", french: "enthousiasme (enthusiasm)"},
{chinese: "认为", pinyin: "rènwéi", french: "penser (think)"},
{chinese: "认真", pinyin: "rènzhēn", french: "sérieux (earnest)"},
{chinese: "容易", pinyin: "róngyì", french: "facilement (easily)"},
{chinese: "如果", pinyin: "rúguǒ", french: "si (if)"},
{chinese: "伞", pinyin: "sǎn", french: "parapluie (umbrella)"},
{chinese: "上网", pinyin: "shàngwǎng", french: "surfer sur internet (surf the internet)"},
{chinese: "生气", pinyin: "shēngqì", french: "se fâcher (get angry)"},
{chinese: "声音", pinyin: "shēngyīn", french: "voix (voice)"},
{chinese: "试", pinyin: "shì", french: "essayer (try)"},
{chinese: "世界", pinyin: "shìjiè", french: "monde (world)"},
{chinese: "瘦", pinyin: "shòu", french: "mince (thin)"},
{chinese: "舒服", pinyin: "shūfu", french: "confortable (comfortable)"},
{chinese: "叔叔", pinyin: "shūshu", french: "oncle (uncle)"},
{chinese: "树", pinyin: "shù", french: "arbre (tree)"},
{chinese: "数学", pinyin: "shùxué", french: "mathématiques (mathematics)"},
{chinese: "刷牙", pinyin: "shuāyá", french: "se brosser les dents (brush one’s teeth)"},
{chinese: "双", pinyin: "shuāng", french: "double, paire (double, pair)"},
{chinese: "水平", pinyin: "shuǐpíng", french: "niveau (level)"},
{chinese: "司机", pinyin: "sījī", french: "chauffeur (driver)"},
{chinese: "太阳", pinyin: "tàiyáng", french: "soleil (sun)"},
{chinese: "特别", pinyin: "tèbié", french: "surtout (especially)"},
{chinese: "疼", pinyin: "téng", french: "blesser (hurt)"},
{chinese: "提高", pinyin: "tígāo", french: "augmenter (increase)"},
{chinese: "体育", pinyin: "tǐyù", french: "sports (sports)"},
{chinese: "甜", pinyin: "tián", french: "doux (sweet)"},
{chinese: "条", pinyin: "tiáo", french: "bande (strip)"},
{chinese: "同事", pinyin: "tóngshì", french: "collègue (colleague)"},
{chinese: "同意", pinyin: "tóngyì", french: "d'accord (agree)"},
{chinese: "头发", pinyin: "tóufa", french: "cheveux (hair)"},
{chinese: "突然", pinyin: "tūrán", french: "soudainement (suddenly)"},
{chinese: "图书馆", pinyin: "túshūguǎn", french: "bibliothèque (library)"},
{chinese: "腿", pinyin: "tuǐ", french: "jambe (leg)"},
{chinese: "完成", pinyin: "wánchéng", french: "terminer (complete)"},
{chinese: "碗", pinyin: "wǎn", french: "bol (bowl)"},
{chinese: "万", pinyin: "wàn", french: "dix mille (ten thousand)"},
{chinese: "忘记", pinyin: "wàngjì", french: "oublier (forget)"},
{chinese: "为", pinyin: "wèi", french: "pour (for)"},
{chinese: "为了", pinyin: "wèile", french: "afin de (in order to)"},
{chinese: "位", pinyin: "wèi", french: "position (position)"},
{chinese: "文化", pinyin: "wénhuà", french: "culture (culture)"},
{chinese: "西", pinyin: "xī", french: "ouest (west)"},
{chinese: "习惯", pinyin: "xíguàn", french: "habitude (habit)"},
{chinese: "洗手间", pinyin: "xǐshǒujiān", french: "toilettes (restroom)"},
{chinese: "洗澡", pinyin: "xǐzǎo", french: "prendre une douche (take a shower)"},
{chinese: "夏", pinyin: "xià", french: "été (summer)"},
{chinese: "先", pinyin: "xiān", french: "d'abord (first)"},
{chinese: "香蕉", pinyin: "xiāngjiāo", french: "banane (banana)"},
{chinese: "相信", pinyin: "xiāngxìn", french: "croire (believe)"},
{chinese: "向", pinyin: "xiàng", french: "vers (towards)"},
{chinese: "像", pinyin: "xiàng", french: "image (image)"},
{chinese: "小心", pinyin: "xiǎoxīn", french: "attention (watch out)"},
{chinese: "校长", pinyin: "xiàozhǎng", french: "directeur (principal)"},
{chinese: "新闻", pinyin: "xīnwén", french: "nouvelles (news)"},
{chinese: "新鲜", pinyin: "xīnxiān", french: "frais (fresh)"},
{chinese: "信用卡", pinyin: "xìnyòngkǎ", french: "carte de crédit (credit card)"},
{chinese: "行李箱", pinyin: "xínglixiāng", french: "coffre (trunk)"},
{chinese: "熊猫", pinyin: "xióngmāo", french: "panda (panda)"},
{chinese: "需要", pinyin: "xūyào", french: "besoin (need)"},
{chinese: "选择", pinyin: "xuǎnzé", french: "choix (choice)"},
{chinese: "要求", pinyin: "yāoqiú", french: "exigence (requirement)"},
{chinese: "爷爷", pinyin: "yéye", french: "grand-père (grandpa)"},
{chinese: "一定", pinyin: "yídìng", french: "certain (certain)"},
{chinese: "一共", pinyin: "yígòng", french: "au total (altogether)"},
{chinese: "一会儿", pinyin: "yíhuìr", french: "un moment (a while)"},
{chinese: "一样", pinyin: "yíyàng", french: "également (equally)"},
{chinese: "以前", pinyin: "yǐqián", french: "avant (before)"},
{chinese: "一般", pinyin: "yìbān", french: "communément (commonly)"},
{chinese: "一边", pinyin: "yìbiān", french: "un côté (one side)"},
{chinese: "一直", pinyin: "yìzhí", french: "toujours (always)"},
{chinese: "音乐", pinyin: "yīnyuè", french: "musique (music)"},
{chinese: "银行", pinyin: "yínháng", french: "banque (bank)"},
{chinese: "饮料", pinyin: "yǐnliào", french: "boissons (drinks)"},
{chinese: "应该", pinyin: "yīnggāi", french: "devrait (should)"},
{chinese: "影响", pinyin: "yǐngxiǎng", french: "influence (influence)"},
{chinese: "用", pinyin: "yòng", french: "utiliser (use)"},
{chinese: "游戏", pinyin: "yóuxì", french: "jeu (game)"},
{chinese: "有名", pinyin: "yǒumíng", french: "célèbre (famous)"},
{chinese: "又", pinyin: "yòu", french: "encore (again)"},
{chinese: "遇到", pinyin: "yùdào", french: "rencontrer (encounter)"},
{chinese: "元", pinyin: "yuán", french: "élément; yuan (element; yuan)"},
{chinese: "愿意", pinyin: "yuànyì", french: "être prêt (be willing)"},
{chinese: "月亮", pinyin: "yuèliang", french: "lune (moon)"},
{chinese: "越", pinyin: "yuè", french: "plus (the more)"},
{chinese: "站", pinyin: "zhàn", french: "station (station)"},
{chinese: "张", pinyin: "zhāng", french: "zhang (nom de famille) (zhang (surname))"},
{chinese: "长（动词）", pinyin: "zhǎng", french: "grandir (grow)"},
{chinese: "着急", pinyin: "zháojí", french: "s'inquiéter (worry)"},
{chinese: "照顾", pinyin: "zhàogù", french: "s'occuper de (look after)"},
{chinese: "照片", pinyin: "zhàopiàn", french: "photo (photo)"},
{chinese: "照相机", pinyin: "zhàoxiàngjī", french: "appareil photo (camera)"},
{chinese: "只（量词）", pinyin: "zhī", french: "(mot de mesure) ((measure word))"},
{chinese: "只（副词）", pinyin: "zhǐ", french: "seulement (only)"},
{chinese: "只有……才……", pinyin: "zhǐyǒu…cái…", french: "seulement si (only if)"},
{chinese: "中文", pinyin: "zhōngwén", french: "chinois (chinese)"},
{chinese: "中间", pinyin: "zhōngjiān", french: "milieu (middle)"},
{chinese: "终于", pinyin: "zhōngyú", french: "finalement (finally)"},
{chinese: "种", pinyin: "zhǒng", french: "espèce (species)"},
{chinese: "重要", pinyin: "zhòngyào", french: "important (important)"},
{chinese: "周末", pinyin: "zhōumò", french: "week-end (weekend)"},
{chinese: "主要", pinyin: "zhǔyào", french: "principal (main)"},
{chinese: "注意", pinyin: "zhùyì", french: "faire attention (be careful)"},
{chinese: "自己", pinyin: "zìjǐ", french: "propre, soi (own, self)"},
{chinese: "自行车", pinyin: "zìxíngchē", french: "vélo (bicycle)"},
{chinese: "总是", pinyin: "zǒngshì", french: "toujours (always)"},
{chinese: "嘴", pinyin: "zuǐ", french: "bouche (mouth)"},
{chinese: "最后", pinyin: "zuìhòu", french: "dernier (last)"},
{chinese: "最近", pinyin: "zuìjìn", french: "récemment (lately)"},
{chinese: "作业", pinyin: "zuòyè", french: "devoirs (homework)"}
];
