export var hsk1 = [
  {chinese: "我", pinyin: "wǒ", french: "I, me"},
  {chinese: "我们", pinyin: "wǒmen", french: "we, us (pl.)"},
  {chinese: "你", pinyin: "nǐ", french: "you"},
  {chinese: "他", pinyin: "tā", french: "he, him"},
  {chinese: "她", pinyin: "tā", french: "she, her"},
  {chinese: "这", pinyin: "zhè", french: "this (here)"},
  {chinese: "那", pinyin: "nà", french: "that (there)"},
  {chinese: "哪", pinyin: "nǎ", french: "which"},
  {chinese: "哪儿", pinyin: "nǎr", french: "where"},
  {chinese: "谁", pinyin: "shéi", french: "who"},
  {chinese: "什么", pinyin: "shénme", french: "what, why"},
  {chinese: "多少", pinyin: "duōshǎo", french: "how many, how much"},
  {chinese: "几", pinyin: "jǐ", french: "a few, how many"},
  {chinese: "怎么", pinyin: "zěnme", french: "how"},
  {chinese: "怎么样", pinyin: "zěnmeyàng", french: "how about"},
  {chinese: "一", pinyin: "yī", french: "one"},
  {chinese: "二", pinyin: "èr", french: "two"},
  {chinese: "三", pinyin: "sān", french: "three"},
  {chinese: "四", pinyin: "sì", french: "four"},
  {chinese: "五", pinyin: "wǔ", french: "five"},
  {chinese: "六", pinyin: "liù", french: "six"},
  {chinese: "七", pinyin: "qī", french: "seven"},
  {chinese: "八", pinyin: "bā", french: "eight"},
  {chinese: "九", pinyin: "jiǔ", french: "nine"},
  {chinese: "十", pinyin: "shí", french: "ten"},
  {chinese: "个", pinyin: "gè", french: "(for normal objects)"},
  {chinese: "岁", pinyin: "suì", french: "(for age)"},
  {chinese: "本", pinyin: "běn", french: "(for books)"},
  {chinese: "些", pinyin: "xiē", french: "some"},
  {chinese: "块", pinyin: "kuài", french: "piece, chunk"},
  {chinese: "不", pinyin: "bù", french: "no"},
  {chinese: "没", pinyin: "méi", french: "no"},
  {chinese: "很", pinyin: "hěn", french: "quite, very"},
  {chinese: "太", pinyin: "tài", french: "too"},
  {chinese: "都", pinyin: "dōu", french: "all"},
  {chinese: "一点儿", pinyin: "yīdiǎnr", french: "a little bit"},
  {chinese: "和", pinyin: "hé", french: "and"},
  {chinese: "在", pinyin: "zài", french: "in, at"},
  {chinese: "的", pinyin: "de", french: "of"},
  {chinese: "了", pinyin: "le", french: "particle indicating change of state"},
  {chinese: "吗", pinyin: "ma", french: "question particle"},
  {chinese: "呢", pinyin: "ne", french: "question particle"},
  {chinese: "喂", pinyin: "wèi", french: "hello"},
  {chinese: "家", pinyin: "jiā", french: "home"},
  {chinese: "学校", pinyin: "xuéxiào", french: "school"},
  {chinese: "饭店", pinyin: "fàndiàn", french: "restaurant"},
  {chinese: "商店", pinyin: "shāngdiàn", french: "store"},
  {chinese: "医院", pinyin: "yīyuàn", french: "hospital"},
  {chinese: "中国", pinyin: "Zhōngguó", french: "China"},
  {chinese: "北京", pinyin: "Běijīng", french: "Beijing"},
  {chinese: "上", pinyin: "shàng", french: "up"},
  {chinese: "下", pinyin: "xià", french: "down"},
  {chinese: "前面", pinyin: "qiánmiàn", french: "front"},
  {chinese: "后面", pinyin: "hòumiàn", french: "behind"},
  {chinese: "里面", pinyin: "lǐmiàn", french: "inside"},
  {chinese: "今天", pinyin: "jīntiān", french: "today"},
  {chinese: "明天", pinyin: "míngtiān", french: "tomorrow"},
  {chinese: "昨天", pinyin: "zuótiān", french: "yesterday"},
  {chinese: "上午", pinyin: "shàngwǔ", french: "morning"},
  {chinese: "中午", pinyin: "zhōngwǔ", french: "noon"},
  {chinese: "下午", pinyin: "xiàwǔ", french: "afternoon"},
  {chinese: "年", pinyin: "nián", french: "year"},
  {chinese: "月", pinyin: "yuè", french: "month"},
  {chinese: "号", pinyin: "hào", french: "number/date"},
  {chinese: "星期", pinyin: "xīngqī", french: "week"},
  {chinese: "点", pinyin: "diǎn", french: "o’clock"},
  {chinese: "分钟", pinyin: "fēnzhōng", french: "minute"},
  {chinese: "现在", pinyin: "xiànzài", french: "now"},
  {chinese: "时候", pinyin: "shíhou", french: "time"},
  {chinese: "爸爸", pinyin: "bàba", french: "father"},
  {chinese: "妈妈", pinyin: "māma", french: "mother"},
  {chinese: "儿子", pinyin: "érzi", french: "son"},
  {chinese: "女儿", pinyin: "nǚér", french: "daughter"},
  {chinese: "老师", pinyin: "lǎoshī", french: "teacher"},
  {chinese: "学生", pinyin: "xuéshēng", french: "student"},
  {chinese: "同学", pinyin: "tóngxué", french: "classmate"},
  {chinese: "朋友", pinyin: "péngyǒu", french: "friend"},
  {chinese: "医生", pinyin: "yīshēng", french: "doctor"},
  {chinese: "先生", pinyin: "xiānsheng", french: "sir"},
  {chinese: "小姐", pinyin: "xiǎojiě", french: "Miss"},
  {chinese: "衣服", pinyin: "yīfu", french: "cloth"},
  {chinese: "水", pinyin: "shuǐ", french: "water"},
  {chinese: "菜", pinyin: "cài", french: "dish"},
  {chinese: "米饭", pinyin: "mǐfàn", french: "rice"},
  {chinese: "水果", pinyin: "shuǐguǒ", french: "fruit"},
  {chinese: "苹果", pinyin: "píngguǒ", french: "apple"},
  {chinese: "茶", pinyin: "chá", french: "tea"},
  {chinese: "杯子", pinyin: "bēizi", french: "cup"},
  {chinese: "钱", pinyin: "qián", french: "money"},
  {chinese: "飞机", pinyin: "fēijī", french: "airplane"},
  {chinese: "出租车", pinyin: "chūzūchē", french: "taxi"},
  {chinese: "电视", pinyin: "diànshì", french: "television"},
  {chinese: "电脑", pinyin: "diànnǎo", french: "computer"},
  {chinese: "电影", pinyin: "diànyǐng", french: "movie"},
  {chinese: "天气", pinyin: "tiānqì", french: "weather"},
  {chinese: "猫", pinyin: "māo", french: "cat"},
  {chinese: "狗", pinyin: "gǒu", french: "dog"},
  {chinese: "东西", pinyin: "dōngxi", french: "thing"},
  {chinese: "人", pinyin: "rén", french: "person"},
  {chinese: "名字", pinyin: "míngzi", french: "name"},
  {chinese: "书", pinyin: "shū", french: "book"},
  {chinese: "汉语", pinyin: "hànyǔ", french: "mandarin Chinese"},
  {chinese: "字", pinyin: "zì", french: "character"},
  {chinese: "桌子", pinyin: "zhuōzi", french: "desk"},
  {chinese: "椅子", pinyin: "yǐzi", french: "chair"},
  {chinese: "谢谢", pinyin: "xièxie", french: "thank"},
  {chinese: "不客气", pinyin: "búkèqì", french: "you are welcome"},
  {chinese: "再见", pinyin: "zàijiàn", french: "good-bye"},
  {chinese: "请", pinyin: "qǐng", french: "please"},
  {chinese: "对不起", pinyin: "duìbùqǐ", french: "sorry"},
  {chinese: "没关系", pinyin: "méiguānxì", french: "It doesn’t matter"},
  {chinese: "是", pinyin: "shì", french: "be (am, is, are)"},
  {chinese: "有", pinyin: "yǒu", french: "have"},
  {chinese: "看", pinyin: "kàn", french: "look"},
  {chinese: "听", pinyin: "tīng", french: "listen"},
  {chinese: "说", pinyin: "shuō", french: "speak"},
  {chinese: "读", pinyin: "dú", french: "read"},
  {chinese: "写", pinyin: "xiě", french: "write"},
  {chinese: "看见", pinyin: "kànjiàn", french: "see"},
  {chinese: "叫", pinyin: "jiào", french: "call"},
  {chinese: "来", pinyin: "lái", french: "come"},
  {chinese: "回", pinyin: "huí", french: "return"},
  {chinese: "去", pinyin: "qù", french: "go"},
  {chinese: "吃", pinyin: "chī", french: "eat"},
  {chinese: "喝", pinyin: "hē", french: "drink"},
  {chinese: "睡觉", pinyin: "shuìjiào", french: "sleep"},
  {chinese: "打电话", pinyin: "dǎdiànhuà", french: "make phone call"},
  {chinese: "做", pinyin: "zuò", french: "do"},
  {chinese: "买", pinyin: "mǎi", french: "buy"},
  {chinese: "开", pinyin: "kāi", french: "open"},
  {chinese: "坐", pinyin: "zuò", french: "sit"},
  {chinese: "住", pinyin: "zhù", french: "live"},
  {chinese: "学习", pinyin: "xuéxí", french: "study"},
  {chinese: "工作", pinyin: "gōngzuò", french: "work"},
  {chinese: "下雨", pinyin: "xiàyǔ", french: "rain"},
  {chinese: "爱", pinyin: "ài", french: "love"},
  {chinese: "喜欢", pinyin: "xǐhuān", french: "love, like"},
  {chinese: "想", pinyin: "xiǎng", french: "want"},
  {chinese: "认识", pinyin: "rènshi", french: "know"},
  {chinese: "会", pinyin: "huì", french: "can"},
  {chinese: "能", pinyin: "néng", french: "can, be able to"},
  {chinese: "好", pinyin: "hǎo", french: "good"},
  {chinese: "大", pinyin: "dà", french: "big"},
  {chinese: "小", pinyin: "xiǎo", french: "small"},
  {chinese: "多", pinyin: "duō", french: "many, much"},
  {chinese: "少", pinyin: "shǎo", french: "few, little"},
  {chinese: "冷", pinyin: "lěng", french: "cold"},
  {chinese: "热", pinyin: "rè", french: "hot"},
  {chinese: "高兴", pinyin: "gāoxìng", french: "happy"},
  {chinese: "漂亮", pinyin: "piàoliang", french: "beautiful"}
];
