export var hsk3 = [
{chinese: "阿姨", pinyin: "āyí", french: "aunt"},
{chinese: "啊", pinyin: "a", french: "ah"},
{chinese: "矮", pinyin: "ǎi", french: "short"},
{chinese: "爱好", pinyin: "àihào", french: "hobby"},
{chinese: "安静", pinyin: "ānjìng", french: "be quiet"},
{chinese: "把", pinyin: "bǎ", french: "hold"},
{chinese: "班", pinyin: "bān", french: "class"},
{chinese: "搬", pinyin: "bān", french: "move"},
{chinese: "半", pinyin: "bàn", french: "half"},
{chinese: "办法", pinyin: "bànfǎ", french: "way"},
{chinese: "办公室", pinyin: "bàngōngshì", french: "office"},
{chinese: "帮忙", pinyin: "bāngmáng", french: "help"},
{chinese: "包", pinyin: "bāo", french: "package"},
{chinese: "饱", pinyin: "bǎo", french: "full"},
{chinese: "北方", pinyin: "běifāng", french: "north"},
{chinese: "被", pinyin: "bèi", french: "cover"},
{chinese: "鼻子", pinyin: "bízi", french: "nose"},
{chinese: "比较", pinyin: "bǐjiào", french: "compare"},
{chinese: "比赛", pinyin: "bǐsài", french: "match"},
{chinese: "笔记本", pinyin: "bǐjìběn", french: "notebook"},
{chinese: "必须", pinyin: "bìxū", french: "must"},
{chinese: "变化", pinyin: "biànhuà", french: "change"},
{chinese: "别人", pinyin: "biéren", french: "others"},
{chinese: "冰箱", pinyin: "bīngxiāng", french: "refrigerator"},
{chinese: "菜单", pinyin: "càidān", french: "menu"},
{chinese: "参加", pinyin: "cānjiā", french: "participate in"},
{chinese: "草", pinyin: "cǎo", french: "grass"},
{chinese: "层", pinyin: "céng", french: "layer"},
{chinese: "差", pinyin: "chà", french: "bad"},
{chinese: "超市", pinyin: "chāoshì", french: "supermarket"},
{chinese: "衬衫", pinyin: "chènshān", french: "shirt"},
{chinese: "成绩", pinyin: "chéngjì", french: "achievement"},
{chinese: "城市", pinyin: "chéngshì", french: "city"},
{chinese: "迟到", pinyin: "chídào", french: "late"},
{chinese: "除了", pinyin: "chúle", french: "except, besides"},
{chinese: "船", pinyin: "chuán", french: "ship"},
{chinese: "春", pinyin: "chūn", french: "spring"},
{chinese: "词典", pinyin: "cídiǎn", french: "dictionaries"},
{chinese: "聪明", pinyin: "cōngming", french: "clever"},
{chinese: "打扫", pinyin: "dǎsǎo", french: "clean"},
{chinese: "打算", pinyin: "dǎsuàn", french: "plan"},
{chinese: "带", pinyin: "dài", french: "belt"},
{chinese: "担心", pinyin: "dānxīn", french: "worry"},
{chinese: "蛋糕", pinyin: "dàngāo", french: "cake"},
{chinese: "当然", pinyin: "dāngrán", french: "of course"},
{chinese: "地", pinyin: "de", french: ""},
{chinese: "灯", pinyin: "dēng", french: "lamp"},
{chinese: "地方", pinyin: "dìfang", french: "local"},
{chinese: "地铁", pinyin: "dìtiě", french: "metro"},
{chinese: "地图", pinyin: "dìtú", french: "map"},
{chinese: "电梯", pinyin: "diàntī", french: "elevator"},
{chinese: "电子邮件", pinyin: "diànzǐyóujiàn", french: "e-mail"},
{chinese: "东", pinyin: "dōng", french: "east"},
{chinese: "冬", pinyin: "dōng", french: "winter"},
{chinese: "动物", pinyin: "dòngwù", french: "animal"},
{chinese: "短", pinyin: "duǎn", french: "short"},
{chinese: "段", pinyin: "duàn", french: "paragraph"},
{chinese: "锻炼", pinyin: "duànliàn", french: "physical exercise"},
{chinese: "多么", pinyin: "duōme", french: "such"},
{chinese: "饿", pinyin: "è", french: "hungry"},
{chinese: "不但……而且……", pinyin: "búdàn…érqiě…", french: "not only…but also…"},
{chinese: "耳朵", pinyin: "ěrduo", french: "ears"},
{chinese: "发", pinyin: "fā", french: "send out"},
{chinese: "发烧", pinyin: "fāshāo", french: "have a fever"},
{chinese: "发现", pinyin: "fāxiàn", french: "find, discover"},
{chinese: "方便", pinyin: "fāngbiàn", french: "convenient"},
{chinese: "放", pinyin: "fàng", french: "discharge"},
{chinese: "放心", pinyin: "fàngxīn", french: "don’t worry"},
{chinese: "分", pinyin: "fēn", french: "minute"},
{chinese: "附近", pinyin: "fùjìn", french: "nearby"},
{chinese: "复习", pinyin: "fùxí", french: "review"},
{chinese: "干净", pinyin: "gānjìng", french: "clean"},
{chinese: "感兴趣", pinyin: "gǎnxìngqù", french: "be interested in"},
{chinese: "感冒", pinyin: "gǎnmào", french: "get a cold"},
{chinese: "刚才", pinyin: "gāngcái", french: "just"},
{chinese: "个子", pinyin: "gèzi", french: "height"},
{chinese: "跟", pinyin: "gēn", french: "with"},
{chinese: "根据", pinyin: "gēnjù", french: "according to"},
{chinese: "更", pinyin: "gèng", french: "more"},
{chinese: "公斤", pinyin: "gōngjīn", french: "kg."},
{chinese: "公园", pinyin: "gōngyuán", french: "park"},
{chinese: "故事", pinyin: "gùshi", french: "story"},
{chinese: "刮风", pinyin: "guāfēng", french: "windy"},
{chinese: "关", pinyin: "guān", french: "shut"},
{chinese: "关系", pinyin: "guānxì", french: "relationship"},
{chinese: "关心", pinyin: "guānxīn", french: "care for"},
{chinese: "关于", pinyin: "guānyú", french: "about"},
{chinese: "国家", pinyin: "guójiā", french: "country"},
{chinese: "过去", pinyin: "guòqù", french: "past times"},
{chinese: "过（动词）", pinyin: "guò", french: "pass"},
{chinese: "还是", pinyin: "háishì", french: "still"},
{chinese: "害怕", pinyin: "hàipà", french: "fear"},
{chinese: "黑板", pinyin: "hēibǎn", french: "blackboard"},
{chinese: "后来", pinyin: "hòulái", french: "later"},
{chinese: "护照", pinyin: "hùzhào", french: "passport"},
{chinese: "花（动词）", pinyin: "huā", french: "spend"},
{chinese: "花（名词）", pinyin: "huā", french: "flower"},
{chinese: "画", pinyin: "huà", french: "painting"},
{chinese: "坏", pinyin: "huài", french: "bad"},
{chinese: "欢迎", pinyin: "huānyíng", french: "welcome"},
{chinese: "还（动词）", pinyin: "huán", french: "return"},
{chinese: "环境", pinyin: "huánjìng", french: "environment"},
{chinese: "换", pinyin: "huàn", french: "change"},
{chinese: "黄河", pinyin: "huánghé", french: "yellow river"},
{chinese: "回答", pinyin: "huídá", french: "answer"},
{chinese: "会议", pinyin: "huìyì", french: "meeting"},
{chinese: "或者", pinyin: "huòzhě", french: "perhaps"},
{chinese: "几乎", pinyin: "jīhū", french: "almost"},
{chinese: "机会", pinyin: "jīhuì", french: "opportunity"},
{chinese: "极", pinyin: "jí", french: "extremely"},
{chinese: "记得", pinyin: "jìde", french: "remember"},
{chinese: "季节", pinyin: "jìjié", french: "season"},
{chinese: "检查", pinyin: "jiǎnchá", french: "inspect"},
{chinese: "简单", pinyin: "jiǎndān", french: "simple"},
{chinese: "健康", pinyin: "jiànkāng", french: "healthy"},
{chinese: "见面", pinyin: "jiànmiàn", french: "meet"},
{chinese: "讲", pinyin: "jiǎng", french: "speak"},
{chinese: "教", pinyin: "jiāo", french: "teach"},
{chinese: "角", pinyin: "jiǎo", french: "horn"},
{chinese: "脚", pinyin: "jiǎo", french: "foot"},
{chinese: "接", pinyin: "jiē", french: "pick, get"},
{chinese: "街道", pinyin: "jiēdào", french: "street"},
{chinese: "结婚", pinyin: "jiéhūn", french: "marry"},
{chinese: "结束", pinyin: "jiéshù", french: "end"},
{chinese: "节目", pinyin: "jiémù", french: "program"},
{chinese: "节日", pinyin: "jiérì", french: "festival"},
{chinese: "解决", pinyin: "jiějué", french: "solve"},
{chinese: "借", pinyin: "jiè", french: "borrow"},
{chinese: "经常", pinyin: "jīngcháng", french: "often"},
{chinese: "经过", pinyin: "jīngguò", french: "after, through"},
{chinese: "经理", pinyin: "jīnglǐ", french: "manager"},
{chinese: "久", pinyin: "jiǔ", french: "long"},
{chinese: "旧", pinyin: "jiù", french: "old, used"},
{chinese: "句子", pinyin: "jùzi", french: "sentence"},
{chinese: "决定", pinyin: "juédìng", french: "decision"},
{chinese: "渴", pinyin: "kě", french: "thirsty"},
{chinese: "可爱", pinyin: "kě’ài", french: "lovely"},
{chinese: "刻", pinyin: "kè", french: "moment"},
{chinese: "客人", pinyin: "kèrén", french: "guest"},
{chinese: "空调", pinyin: "kōngtiáo", french: "air conditioner"},
{chinese: "口", pinyin: "kǒu", french: "mouth"},
{chinese: "哭", pinyin: "kū", french: "cry"},
{chinese: "裤子", pinyin: "kùzi", french: "trousers"},
{chinese: "筷子", pinyin: "kuàizi", french: "chopsticks"},
{chinese: "蓝", pinyin: "lán", french: "blue"},
{chinese: "老", pinyin: "lǎo", french: "old"},
{chinese: "离开", pinyin: "líkāi", french: "leave"},
{chinese: "礼物", pinyin: "lǐwù", french: "gift"},
{chinese: "历史", pinyin: "lìshǐ", french: "history"},
{chinese: "脸", pinyin: "liǎn", french: "face"},
{chinese: "聊天", pinyin: "liáotiān", french: "chat"},
{chinese: "练习", pinyin: "liànxí", french: "practice"},
{chinese: "辆", pinyin: "liàng", french: "car"},
{chinese: "了解", pinyin: "liǎojiě", french: "understand"},
{chinese: "邻居", pinyin: "línjū", french: "neighbor"},
{chinese: "留学", pinyin: "liúxué", french: "overseas study"},
{chinese: "楼", pinyin: "lóu", french: "floor"},
{chinese: "绿", pinyin: "lǜ", french: "green"},
{chinese: "马", pinyin: "mǎ", french: "horse"},
{chinese: "马上", pinyin: "mǎshàng", french: "right off"},
{chinese: "满意", pinyin: "mǎnyì", french: "satisfied"},
{chinese: "帽子", pinyin: "màozi", french: "hat"},
{chinese: "米", pinyin: "mǐ", french: "rice"},
{chinese: "面包", pinyin: "miànbāo", french: "bread"},
{chinese: "明白", pinyin: "míngbai", french: "clear"},
{chinese: "拿", pinyin: "ná", french: "take"},
{chinese: "奶奶", pinyin: "nǎinai", french: "grandma"},
{chinese: "南", pinyin: "nán", french: "south"},
{chinese: "难", pinyin: "nán", french: "difficult"},
{chinese: "难过", pinyin: "nánguò", french: "sad"},
{chinese: "年级", pinyin: "niánjí", french: "grade"},
{chinese: "年轻", pinyin: "niánqīng", french: "young"},
{chinese: "鸟", pinyin: "niǎo", french: "bird"},
{chinese: "努力", pinyin: "nǔlì", french: "strive"},
{chinese: "爬山", pinyin: "páshān", french: "mountain climbing"},
{chinese: "盘子", pinyin: "pánzi", french: "plate"},
{chinese: "胖", pinyin: "pàng", french: "fat"},
{chinese: "啤酒", pinyin: "píjiǔ", french: "beer"},
{chinese: "皮鞋", pinyin: "píxié", french: "leather shoes"},
{chinese: "瓶子", pinyin: "píngzi", french: "bottle"},
{chinese: "其实", pinyin: "qíshí", french: "actually"},
{chinese: "其他", pinyin: "qítā", french: "other"},
{chinese: "骑", pinyin: "qí", french: "ride"},
{chinese: "奇怪", pinyin: "qíguài", french: "strange"},
{chinese: "起来", pinyin: "qǐlái", french: "get up"},
{chinese: "起飞", pinyin: "qǐfēi", french: "take off"},
{chinese: "清楚", pinyin: "qīngchu", french: "clear"},
{chinese: "请假", pinyin: "qǐngjià", french: "ask for leave"},
{chinese: "秋", pinyin: "qiū", french: "autumn"},
{chinese: "裙子", pinyin: "qúnzi", french: "skirt"},
{chinese: "然后", pinyin: "ránhòu", french: "then"},
{chinese: "热情", pinyin: "rèqíng", french: "enthusiasm"},
{chinese: "认为", pinyin: "rènwéi", french: "think"},
{chinese: "认真", pinyin: "rènzhēn", french: "earnest"},
{chinese: "容易", pinyin: "róngyì", french: "easily"},
{chinese: "如果", pinyin: "rúguǒ", french: "if"},
{chinese: "伞", pinyin: "sǎn", french: "umbrella"},
{chinese: "上网", pinyin: "shàngwǎng", french: "surf the internet"},
{chinese: "生气", pinyin: "shēngqì", french: "get angry"},
{chinese: "声音", pinyin: "shēngyīn", french: "voice"},
{chinese: "试", pinyin: "shì", french: "try"},
{chinese: "世界", pinyin: "shìjiè", french: "world"},
{chinese: "瘦", pinyin: "shòu", french: "thin"},
{chinese: "舒服", pinyin: "shūfu", french: "comfortable"},
{chinese: "叔叔", pinyin: "shūshu", french: "uncle"},
{chinese: "树", pinyin: "shù", french: "tree"},
{chinese: "数学", pinyin: "shùxué", french: "mathematics"},
{chinese: "刷牙", pinyin: "shuāyá", french: "brush one’s teeth"},
{chinese: "双", pinyin: "shuāng", french: "double, pair"},
{chinese: "水平", pinyin: "shuǐpíng", french: "level"},
{chinese: "司机", pinyin: "sījī", french: "driver"},
{chinese: "太阳", pinyin: "tàiyáng", french: "sun"},
{chinese: "特别", pinyin: "tèbié", french: "especially"},
{chinese: "疼", pinyin: "téng", french: "hurt"},
{chinese: "提高", pinyin: "tígāo", french: "increase"},
{chinese: "体育", pinyin: "tǐyù", french: "sports"},
{chinese: "甜", pinyin: "tián", french: "sweet"},
{chinese: "条", pinyin: "tiáo", french: "strip"},
{chinese: "同事", pinyin: "tóngshì", french: "colleague"},
{chinese: "同意", pinyin: "tóngyì", french: "agree"},
{chinese: "头发", pinyin: "tóufa", french: "hair"},
{chinese: "突然", pinyin: "tūrán", french: "suddenly"},
{chinese: "图书馆", pinyin: "túshūguǎn", french: "library"},
{chinese: "腿", pinyin: "tuǐ", french: "leg"},
{chinese: "完成", pinyin: "wánchéng", french: "complete"},
{chinese: "碗", pinyin: "wǎn", french: "bowl"},
{chinese: "万", pinyin: "wàn", french: "ten thousand"},
{chinese: "忘记", pinyin: "wàngjì", french: "forget"},
{chinese: "为", pinyin: "wèi", french: "for"},
{chinese: "为了", pinyin: "wèile", french: "in order to"},
{chinese: "位", pinyin: "wèi", french: "position"},
{chinese: "文化", pinyin: "wénhuà", french: "culture"},
{chinese: "西", pinyin: "xī", french: "west"},
{chinese: "习惯", pinyin: "xíguàn", french: "habit"},
{chinese: "洗手间", pinyin: "xǐshǒujiān", french: "restroom"},
{chinese: "洗澡", pinyin: "xǐzǎo", french: "take a shower"},
{chinese: "夏", pinyin: "xià", french: "summer"},
{chinese: "先", pinyin: "xiān", french: "first"},
{chinese: "香蕉", pinyin: "xiāngjiāo", french: "banana"},
{chinese: "相信", pinyin: "xiāngxìn", french: "believe"},
{chinese: "向", pinyin: "xiàng", french: "towards"},
{chinese: "像", pinyin: "xiàng", french: "image"},
{chinese: "小心", pinyin: "xiǎoxīn", french: "watch out"},
{chinese: "校长", pinyin: "xiàozhǎng", french: "principal"},
{chinese: "新闻", pinyin: "xīnwén", french: "news"},
{chinese: "新鲜", pinyin: "xīnxiān", french: "fresh"},
{chinese: "信用卡", pinyin: "xìnyòngkǎ", french: "credit card"},
{chinese: "行李箱", pinyin: "xínglixiāng", french: "trunk"},
{chinese: "熊猫", pinyin: "xióngmāo", french: "panda"},
{chinese: "需要", pinyin: "xūyào", french: "need"},
{chinese: "选择", pinyin: "xuǎnzé", french: "choice"},
{chinese: "要求", pinyin: "yāoqiú", french: "requirement"},
{chinese: "爷爷", pinyin: "yéye", french: "grandpa"},
{chinese: "一定", pinyin: "yídìng", french: "certain"},
{chinese: "一共", pinyin: "yígòng", french: "altogether"},
{chinese: "一会儿", pinyin: "yíhuìr", french: "a while"},
{chinese: "一样", pinyin: "yíyàng", french: "equally"},
{chinese: "以前", pinyin: "yǐqián", french: "before"},
{chinese: "一般", pinyin: "yìbān", french: "commonly"},
{chinese: "一边", pinyin: "yìbiān", french: "one side"},
{chinese: "一直", pinyin: "yìzhí", french: "always"},
{chinese: "音乐", pinyin: "yīnyuè", french: "music"},
{chinese: "银行", pinyin: "yínháng", french: "bank"},
{chinese: "饮料", pinyin: "yǐnliào", french: "drinks"},
{chinese: "应该", pinyin: "yīnggāi", french: "should"},
{chinese: "影响", pinyin: "yǐngxiǎng", french: "influence"},
{chinese: "用", pinyin: "yòng", french: "use"},
{chinese: "游戏", pinyin: "yóuxì", french: "game"},
{chinese: "有名", pinyin: "yǒumíng", french: "famous"},
{chinese: "又", pinyin: "yòu", french: "again"},
{chinese: "遇到", pinyin: "yùdào", french: "encounter"},
{chinese: "元", pinyin: "yuán", french: "element; yuan"},
{chinese: "愿意", pinyin: "yuànyì", french: "be willing"},
{chinese: "月亮", pinyin: "yuèliang", french: "moon"},
{chinese: "越", pinyin: "yuè", french: "the more"},
{chinese: "站", pinyin: "zhàn", french: "station"},
{chinese: "张", pinyin: "zhāng", french: "zhang (surname)"},
{chinese: "长（动词）", pinyin: "zhǎng", french: "grow"},
{chinese: "着急", pinyin: "zháojí", french: "worry"},
{chinese: "照顾", pinyin: "zhàogù", french: "look after"},
{chinese: "照片", pinyin: "zhàopiàn", french: "photo"},
{chinese: "照相机", pinyin: "zhàoxiàngjī", french: "camera"},
{chinese: "只（量词）", pinyin: "zhī", french: "(measure word)"},
{chinese: "只（副词）", pinyin: "zhǐ", french: "only"},
{chinese: "只有……才……", pinyin: "zhǐyǒu…cái…", french: "only if"},
{chinese: "中文", pinyin: "zhōngwén", french: "chinese"},
{chinese: "中间", pinyin: "zhōngjiān", french: "middle"},
{chinese: "终于", pinyin: "zhōngyú", french: "finally"},
{chinese: "种", pinyin: "zhǒng", french: "species"},
{chinese: "重要", pinyin: "zhòngyào", french: "important"},
{chinese: "周末", pinyin: "zhōumò", french: "weekend"},
{chinese: "主要", pinyin: "zhǔyào", french: "main"},
{chinese: "注意", pinyin: "zhùyì", french: "be careful"},
{chinese: "自己", pinyin: "zìjǐ", french: "own, self"},
{chinese: "自行车", pinyin: "zìxíngchē", french: "bicycle"},
{chinese: "总是", pinyin: "zǒngshì", french: "always"},
{chinese: "嘴", pinyin: "zuǐ", french: "mouth"},
{chinese: "最后", pinyin: "zuìhòu", french: "last"},
{chinese: "最近", pinyin: "zuìjìn", french: "lately"},
{chinese: "作业", pinyin: "zuòyè", french: "homework"}
];