while True: 
    answer = input(">")
    # replace all the '' by '
    replace = answer.replace("''", "?|?")
    
    replace = replace.replace("'e", "é")
    replace = replace.replace("`e", "è")
    replace = replace.replace('^e', "ê")
    replace = replace.replace('"e', "ë")
    replace = replace.replace("'o", "ó")
    replace = replace.replace("^o", "ô")
    replace = replace.replace("oe", "œ")
    replace = replace.replace("'a", "á")
    replace = replace.replace("`a", "à")
    replace = replace.replace("^a", "â")
    replace = replace.replace("'u", "ú")
    replace = replace.replace("`u", "û")
    replace = replace.replace("^u", "ù")
    replace = replace.replace("'i", "í")
    replace = replace.replace("^i", "î")
    replace = replace.replace('"i', "ï")
    replace = replace.replace(",c", "ç")
    
    replace = replace.replace("'E", "É")
    replace = replace.replace("`E", "È")
    replace = replace.replace("^E", "Ê")
    replace = replace.replace('"E', "Ë")
    replace = replace.replace("'O", "Ó")
    replace = replace.replace("^O", "Ô")
    replace = replace.replace("OE", "Œ")
    replace = replace.replace("'A", "Á")
    replace = replace.replace("`A", "À")
    replace = replace.replace("^A", "Â")
    replace = replace.replace("'U", "Ú")
    replace = replace.replace("^U", "Û")
    replace = replace.replace("`U", "Ù")
    replace = replace.replace("'I", "Í")
    replace = replace.replace("^I", "Î")
    replace = replace.replace('"I', "Ï")
    replace = replace.replace(",C", "Ç")
    
    replace = replace.replace("?|?", "'")
    
    print(replace)