var pages = [
  "https://timothee123456.github.io/ai_image/future/cities(1).html",
  "https://timothee123456.github.io/ai_image/future/cities(2).html",
  "https://timothee123456.github.io/ai_image/future/cities(3).html",
  "https://timothee123456.github.io/ai_image/future/cities(4).html",
  "https://timothee123456.github.io/ai_image/future/cities(5).html",
  "https://timothee123456.github.io/ai_image/future/cities(6).html",
  "https://timothee123456.github.io/ai_image/future/cities(7).html",
  "https://timothee123456.github.io/ai_image/future/cities(8).html",
  "https://timothee123456.github.io/ai_image/future/cities(9).html",
  "https://timothee123456.github.io/ai_image/future/cities(10).html",
  "https://timothee123456.github.io/ai_image/future/cities(11).html",
  "https://timothee123456.github.io/ai_image/future/cars(1).html",
  "https://timothee123456.github.io/ai_image/future/cars(2).html",
  "https://timothee123456.github.io/ai_image/future/cars(3).html",
  "https://timothee123456.github.io/ai_image/future/cars(4).html",
  "https://timothee123456.github.io/ai_image/future/cars(5).html",
  "https://timothee123456.github.io/ai_image/future/ships(1).html",
  "https://timothee123456.github.io/ai_image/future/ships(2).html",
  "https://timothee123456.github.io/ai_image/future/ships(3).html",
  "https://timothee123456.github.io/ai_image/future/planes(1).html",
  "https://timothee123456.github.io/ai_image/future/planes(2).html",
  "https://timothee123456.github.io/ai_image/future/underwater_cities(1).html",
  "https://timothee123456.github.io/ai_image/future/underwater_cities(2).html",
  "https://timothee123456.github.io/ai_image/future/underwater_cities(3).html",
  "https://timothee123456.github.io/ai_image/future/underwater_cities(4).html",
  // Add more pages here as needed
];
