let flashcards = [
  { chinese: "身体", pinyin: "shēnti", french: "Corps" },
  { chinese: "外貌", pinyin: "wàimào", french: "Apparence" },
  { chinese: "眼睛", pinyin: "yǎnjīng", french: "yeux" },
  { chinese: "鼻子", pinyin: "bízi", french: "nez" },
  { chinese: "耳朵", pinyin: "ěrduo", french: "oreille" },
  { chinese: "个子", pinyin: "gèzi", french: "taille" },
  { chinese: "胳膊", pinyin: "gē bo", french: "bras" },
  { chinese: "腿", pinyin: "tuǐ", french: "jambe" },
  { chinese: "嘴", pinyin: "zuǐ", french: "bouche" },
  { chinese: "脚", pinyin: "jiǎo", french: "pied" },
  { chinese: "背", pinyin: "bèi", french: "dos" },
  { chinese: "头发", pinyin: "tóufà", french: "cheveux" },
  { chinese: "手", pinyin: "shǒu", french: "main" },
  { chinese: "脸", pinyin: "liǎn", french: "visage" },
  { chinese: "短", pinyin: "duǎn", french: "court" },
  { chinese: "颜色", pinyin: "yánsè", french: "couleur" },
  { chinese: "高", pinyin: "gāo", french: "grand" },
  { chinese: "矮", pinyin: "ǎi", french: "petit (en taille)" },
  { chinese: "胖", pinyin: "pàng", french: "gros" },
  { chinese: "瘦", pinyin: "shòu", french: "mince" },
  { chinese: "圆", pinyin: "yuán", french: "rond" },
  { chinese: "尖", pinyin: "jiān", french: "pointu" },
  { chinese: "卷卷的", pinyin: "juǎnjuǎn de", french: "bouclé" },
  { chinese: "乱", pinyin: "luàn", french: "messy" },
  { chinese: "长长的", pinyin: "chángchángde", french: "long" },
  { chinese: "直直的", pinyin: "zhízhíde", french: "droit" }
];
