var title = {chinese: "性格", pinyin: "xìng gé", french: "personnalité"}

var flashcards = [
{ chinese: "性格", pinyin: "xìng gé", french: "personnalité" },
{ chinese: "风格", pinyin: "fēng gé", french: "style" },
{ chinese: "酷", pinyin: "kù", french: "cool" },
{ chinese: "冷", pinyin: "lěng", french: "froid" },
{ chinese: "爱玩儿", pinyin: "ài wánr", french: "aimer jouer" },
{ chinese: "爱开玩笑", pinyin: "ài kāiwánxiào", french: "aimer faire des blagues" },
{ chinese: "自然", pinyin: "zìrán", french: "naturel" },
{ chinese: "假", pinyin: "jiǎ", french: "faux" },
{ chinese: "开朗", pinyin: "kāi lǎng", french: "joyeux, ouvert" },
{ chinese: "帅哥", pinyin: "shuàigē", french: "beau gosse" },
{ chinese: "小鲜肉", pinyin: "xiǎo xiān ròu", french: "jeune, frais (doué de talent, qui a du look)" },
{ chinese: "校花", pinyin: "xiào huā", french: "la fille populaire de l'école" },
{ chinese: "热情", pinyin: "rèqíng", french: "chaleureux" },
{ chinese: "淘气", pinyin: "táo qì", french: "coquin" },
{ chinese: "做自己", pinyin: "zuò zìjǐ", french: "être soi-même" },
{ chinese: "骄傲", pinyin: "jiāo ào", french: "fier" },
{ chinese: "美女", pinyin: "měinǚ", french: "belle fille" },
{ chinese: "校草", pinyin: "xiào cǎo", french: "le garçon populaire de l'école" },
{ chinese: "自信", pinyin: "zìxìn", french: "confiance en soi" },
{ chinese: "靓", pinyin: "liàng", french: "beau, bon, joli" },
{ chinese: "有 个性", pinyin: "yǒu gèxìng", french: "a de la forte personnalité" },
{ chinese: "热心", pinyin: "rèxīn", french: "gentil" },
{ chinese: "靓仔", pinyin: "liàng zǎi", french: "beau garçon" },
{ chinese: "青见女", pinyin: "qīng jiàn nǚ", french: "belle fille" },
{ chinese: "坏", pinyin: "huài", french: "méchant"},
{ chinese: "学习好", pinyin: "xué xí hǎo", french: "bon élève" },
{ chinese: "班长", pinyin: "bān zhǎng", french: "chef de classe" },
{ chinese: "用功", pinyin: "yòng gōng", french: "studieux" },
{ chinese: "理想的", pinyin: "lǐ xiǎng de", french: "idéal" },
{ chinese: "安静", pinyin: "ān jìng", french: "silencieux, calme" }
];
